(()=>{
const API='https://qxwvuxkbcghbkztjrzon.supabase.co/rest/v1/';
const token=()=>{try{return JSON.parse(localStorage.getItem('alban_admin_session')||'null')?.access_token||''}catch{return ''}};
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})}});const t=await r.text();let d=t?JSON.parse(t):null;if(!r.ok)throw Error(d?.message||d?.error||'حدث خطأ');return d}
async function load(){const c=document.getElementById('content');if(!c)return;try{const [ds,bs]=await Promise.all([api('drivers?select=*&order=created_at.desc'),api('branches?select=id,name_ar&order=name_ar')]);window.__afDrivers=ds;window.__afBranches=bs;c.innerHTML=`<div class="card"><div class="section-head"><h2>السائقين</h2><button class="btn" id="afAddDriver">+ إضافة سائق</button></div><div class="table-wrap"><table><thead><tr><th>السائق</th><th>الهاتف</th><th>الفرع</th><th>المركبة</th><th>التوافر</th><th>الحالة</th><th></th></tr></thead><tbody>${ds.map(d=>`<tr><td>${esc(d.name_ar)}</td><td>${esc(d.phone)}</td><td>${esc(bs.find(b=>b.id===d.branch_id)?.name_ar||'—')}</td><td>${esc(d.vehicle_type||'—')} ${esc(d.vehicle_number||'')}</td><td><button class="status ${d.is_available?'on':'off'}" data-av="${d.id}" data-v="${d.is_available}">${d.is_available?'متاح':'مشغول'}</button></td><td><button class="status ${d.is_active?'on':'off'}" data-act="${d.id}" data-v="${d.is_active}">${d.is_active?'نشط':'متوقف'}</button></td><td><button class="small" data-edit-driver="${d.id}">تعديل</button></td></tr>`).join('')||'<tr><td colspan="7">لا يوجد سائقون</td></tr>'}</tbody></table></div></div>`;afAddDriver.onclick=()=>form({});document.querySelectorAll('[data-edit-driver]').forEach(x=>x.onclick=()=>form(ds.find(d=>d.id===x.dataset.editDriver)));document.querySelectorAll('[data-av]').forEach(x=>x.onclick=async()=>{try{await api(`drivers?id=eq.${x.dataset.av}`,{method:'PATCH',body:JSON.stringify({is_available:x.dataset.v!=='true'})});load()}catch(e){alert(e.message)}});document.querySelectorAll('[data-act]').forEach(x=>x.onclick=async()=>{try{await api(`drivers?id=eq.${x.dataset.act}`,{method:'PATCH',body:JSON.stringify({is_active:x.dataset.v!=='true'})});load()}catch(e){alert(e.message)}})}catch(e){c.innerHTML=`<div class="card"><div class="notice">${esc(e.message)}</div></div>`}}
function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function form(d){const c=document.getElementById('content');c.innerHTML=`<div class="card"><h2>${d.id?'تعديل السائق':'إضافة سائق'}</h2><div class="form-grid"><div class="field"><label>الاسم بالعربي</label><input id="af_ar" value="${esc(d.name_ar)}"></div><div class="field"><label>الاسم بالإنجليزي</label><input id="af_en" value="${esc(d.name_en)}"></div><div class="field"><label>الهاتف</label><input id="af_phone" value="${esc(d.phone)}"></div><div class="field"><label>الفرع</label><select id="af_branch">${(window.__afBranches||[]).map(b=>`<option value="${b.id}" ${d.branch_id===b.id?'selected':''}>${esc(b.name_ar)}</option>`).join('')}</select></div><div class="field"><label>نوع المركبة</label><input id="af_vehicle" value="${esc(d.vehicle_type)}"></div><div class="field"><label>رقم المركبة</label><input id="af_number" value="${esc(d.vehicle_number)}"></div></div><button class="btn" id="afSave">حفظ</button> <button class="small" id="afCancel">إلغاء</button></div>`;afCancel.onclick=load;afSave.onclick=async()=>{const p={name_ar:af_ar.value.trim(),name_en:af_en.value.trim()||null,phone:af_phone.value.trim()||null,branch_id:af_branch.value||null,vehicle_type:af_vehicle.value.trim()||null,vehicle_number:af_number.value.trim()||null};try{if(d.id)await api(`drivers?id=eq.${d.id}`,{method:'PATCH',body:JSON.stringify(p)});else await api('drivers',{method:'POST',body:JSON.stringify({...p,is_active:true,is_available:true})});load()}catch(e){alert(e.message)}}}
function watch(){document.querySelectorAll('[data-page="drivers"]').forEach(b=>{if(!b.dataset.afBound){b.dataset.afBound='1';b.addEventListener('click',()=>setTimeout(load,80))}})}
new MutationObserver(watch).observe(document.body,{childList:true,subtree:true});watch();
})();