const SUPABASE_URL='https://qxwvuxkbcghbkztjrzon.supabase.co';
const AUTH_FUNCTION=`${SUPABASE_URL}/functions/v1/admin-auth`;
const nav=[['dashboard','📊','الرئيسية'],['branches','🏪','الفروع'],['categories','📂','الأقسام'],['products','🧀','المنتجات'],['availability','🟢','التوافر'],['orders','🛵','الطلبات'],['customers','👥','العملاء'],['drivers','🚗','السائقين'],['offers','🎁','العروض'],['reports','📈','التقارير']];
const app=document.getElementById('app'); let current='dashboard'; let session=null; let me=null;
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function login(){app.innerHTML=`<div class="login-wrap"><div class="login-card"><div class="brand">🥛 ألبان فلاحي</div><h1>دخول الإدارة</h1><p>سجّل الدخول بحساب الإدارة المصرح له.</p><form id="loginForm"><input id="email" type="email" autocomplete="username" placeholder="البريد الإلكتروني" required><input id="password" type="password" autocomplete="current-password" placeholder="كلمة المرور" required><button>دخول</button><div id="loginError" class="error"></div></form></div></div>`;document.getElementById('loginForm').onsubmit=doLogin;}
async function doLogin(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='جاري الدخول...';document.getElementById('loginError').textContent='';try{const r=await fetch(AUTH_FUNCTION,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('email').value.trim(),password:document.getElementById('password').value})});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر تسجيل الدخول');session=d.session;me=d.user;localStorage.setItem('alban_admin_session',JSON.stringify(session));localStorage.setItem('alban_admin_user',JSON.stringify(me));renderShell();await renderPage();}catch(err){document.getElementById('loginError').textContent=err.message;}finally{btn.disabled=false;btn.textContent='دخول';}}
function logout(){session=null;me=null;localStorage.removeItem('alban_admin_session');localStorage.removeItem('alban_admin_user');login();}
function authHeaders(){return {'apikey':'public','Authorization':`Bearer ${session?.access_token||''}`,'Content-Type':'application/json','Prefer':'return=representation'}}
async function get(path){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:authHeaders()});if(r.status===401||r.status===403){logout();return []}return r.ok?r.json():[];}
function renderShell(){app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand">🥛 ألبان فلاحي</div><div class="nav">${nav.map(x=>`<button class="${x[0]===current?'active':''}" data-page="${x[0]}">${x[1]} &nbsp; ${x[2]}</button>`).join('')}</div><button class="logout" id="logout">🚪 تسجيل الخروج</button></aside><main class="main"><div class="top"><div><div class="title">${nav.find(x=>x[0]===current)?.[2]||'الرئيسية'}</div><div class="sub">إدارة نظام ألبان فلاحي للتوصيل</div></div><div class="user">👤 ${esc(me?.profile?.full_name||'مدير النظام')}<small>${esc(me?.role||'')}</small></div></div><div id="content"></div></main></div>`;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{current=b.dataset.page;renderShell();renderPage()});document.getElementById('logout').onclick=logout;}
async function renderPage(){const c=document.getElementById('content');if(current==='dashboard'){const [branches,cats,products,orders,customers]=await Promise.all([get('branches?select=id,is_active'),get('categories?select=id,is_active'),get('products?select=id,is_active'),get('orders?select=id,status'),get('customers?select=id')]);c.innerHTML=`<div class="cards"><div class="card"><div class="label">الفروع</div><div class="value">${branches.length}</div></div><div class="card"><div class="label">الأقسام</div><div class="value">${cats.length}</div></div><div class="card"><div class="label">المنتجات</div><div class="value">${products.length}</div></div><div class="card"><div class="label">الطلبات</div><div class="value">${orders.length}</div></div><div class="card"><div class="label">العملاء</div><div class="value">${customers.length}</div></div></div><div class="section"><h2>الفروع</h2><div class="branch-grid">${branches.length?branches.map(b=>`<div class="card branch"><span>🏪 فرع</span><span class="badge">${b.is_active?'نشط':'غير نشط'}</span></div>`).join(''):'<div class="card empty">لا توجد بيانات بعد</div>'}</div></div>`;return;}const labels={branches:'إدارة الفروع وإضافة فرع جديد',categories:'إدارة الأقسام والصور والترتيب',products:'إضافة وتعديل المنتجات والأسعار',availability:'تفعيل وتعطيل المنتجات لكل فرع',orders:'متابعة الطلبات وحالاتها',customers:'بيانات العملاء وطلبات إعادة الشراء',drivers:'إدارة السائقين وتوزيع الطلبات',offers:'العروض والكوبونات',reports:'تقارير المبيعات والأداء'};c.innerHTML=`<div class="card"><h2>${labels[current]}</h2><div class="notice">تم تأمين دخول الإدارة. هذه الشاشة جاهزة للربط بالعمليات التالية.</div></div>`;}
const saved=localStorage.getItem('alban_admin_session');const savedUser=localStorage.getItem('alban_admin_user');if(saved&&savedUser){try{session=JSON.parse(saved);me=JSON.parse(savedUser);renderShell();renderPage();}catch{login();}}else login();