(()=>{const API='https://qxwvuxkbcghbkztjrzon.supabase.co/functions/v1/customer-push';const SUPA='https://qxwvuxkbcghbkztjrzon.supabase.co';const KEY='sb_publishable_JI9lC4YPTCQ8CwMxzvHNIA_C24ULpWH';function session(){try{return JSON.parse(localStorage.getItem('alban_auth_session')||'null')}catch{return null}}function customerId(){return localStorage.getItem('alban_customer_id')||''}function bytes(b){const p='='.repeat((4-b.length%4)%4),s=(b+p).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}async function register(ask=false){try{if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))return{ok:false,reason:'unsupported'};const s=session(),cid=customerId();if(!s?.access_token||!cid)return{ok:false,reason:'login'};if(Notification.permission==='default'&&ask){const p=await Notification.requestPermission();if(p!=='granted')return{ok:false,reason:'denied'}}if(Notification.permission!=='granted')return{ok:false,reason:'denied'};const reg=await navigator.serviceWorker.register('/pwa-sw.js?v=5',{scope:'/'});const kr=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+s.access_token},body:JSON.stringify({action:'public_key'})});const kd=await kr.json();if(!kr.ok||!kd.public_key)return{ok:false,reason:'key'};let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes(kd.public_key)});const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+s.access_token},body:JSON.stringify({action:'subscribe',customer_id:cid,subscription:sub.toJSON()})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)return{ok:false,reason:d.error||'save'};return{ok:true}}catch(e){console.warn('customer push',e);return{ok:false,reason:e.message||'error'}}}window.enableCustomerPush=()=>register(true);
window.syncCustomerPush=()=>register(false);
window.requestCustomerAvailabilityAlert=async(productId,branchId)=>{
 try{
  const push=await register(true);
  if(!push.ok)return push;
  const s=session(),cid=customerId();
  const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+s.access_token},body:JSON.stringify({action:'request_availability_alert',customer_id:cid,product_id:String(productId||''),branch_id:String(branchId||'')})});
  const d=await r.json().catch(()=>({}));
  if(!r.ok||!d.success)return{ok:false,reason:d.error||'save'};
  return{ok:true};
 }catch(e){console.warn('availability alert',e);return{ok:false,reason:e.message||'error'}}
};
})();