(()=>{
const U='https://qxwvuxkbcghbkztjrzon.supabase.co',K='sb_publishable_JI9lC4YPTCQ8CwMxzvHNIA_C24ULpWH';
const money=n=>(Math.round(Number(n||0)*100)/100).toFixed(2),ai=n=>String(Math.max(0,Math.floor(Number(n||0)))).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[d]);
let balance=0,value=.005,pointsEnabled=false;
async function loadPoints(){const id=localStorage.getItem('alban_customer_id');if(!id)return;try{const r=await fetch(U+'/rest/v1/rpc/get_customer_points_balance',{method:'POST',headers:{'Content-Type':'application/json',apikey:K,Authorization:'Bearer '+K},body:JSON.stringify({p_customer_id:id})});const j=await r.json();if(!r.ok||j.error)throw Error(j.error||'points');balance=Number(j.points||0);value=Number(j.point_value_egp||.005);syncUI()}catch(e){console.error('points balance',e)}}
function wanted(){if(!pointsEnabled||balance<=0)return 0;let sub=0;try{const t=window.totals?.();sub=Number(t?.subtotal||t?.sub||0)}catch{}if(!sub&&Array.isArray(window.cart)&&Array.isArray(window.products)){sub=window.cart.reduce((s,x)=>{const p=window.products.find(p=>String(p.id)===String(x.product_id));return s+(Number(p?.base_price||0)*Number(x.quantity||0))},0)}return Math.max(0,Math.min(balance,Math.floor(sub/Math.max(value,.000001))))}
function syncUI(){const cash=balance*value;const p=document.getElementById('points');if(p)p.innerHTML='🎁 البونص: <strong>'+ai(balance)+' نقطة = '+money(cash)+' ج.م</strong>';const h=document.getElementById('bonusText');if(h)h.textContent='متاح '+ai(balance)+' نقطة = '+money(cash)+' ج.م';const b=document.getElementById('bonusBtn');if(b){b.classList.toggle('active',pointsEnabled);b.textContent=pointsEnabled?'إلغاء استخدام البونص':'استخدام البونص'}const d=document.getElementById('bonusDiscount');if(d){const u=wanted();d.textContent=u?'خصم البونص: '+money(u*value)+' ج.م ('+ai(u)+' نقطة)':'';d.className='bonusHint discount'}if(typeof window.renderCart==='function'&&!syncUI.busy){syncUI.busy=true;try{window.renderCart()}catch{}syncUI.busy=false}}
window.toggleBonus=function(){if(balance<=0){alert('لا يوجد رصيد بونص متاح حاليًا');return}pointsEnabled=!pointsEnabled;syncUI()};
const originalFetch=window.fetch.bind(window);window.fetch=async function(input,init){let url=typeof input==='string'?input:input?.url||'';if(url.includes('/rest/v1/rpc/create_customer_order')&&init?.body){try{const body=JSON.parse(init.body);body._points_to_use=wanted();init={...init,body:JSON.stringify(body)};}catch{}}const res=await originalFetch(input,init);if(url.includes('/rest/v1/rpc/create_customer_order')){try{const clone=res.clone(),j=await clone.json();if(j?.order){const used=Number(j.points_used||0),disc=Number(j.points_discount||0),bal=Number(j.points_balance||0);const s=document.getElementById('successText');if(s)s.innerHTML='رقم الطلب: <strong>#'+j.order.order_number+'</strong><br>خصم البونص: <strong>'+money(disc)+' ج.م</strong><br>النقاط المستخدمة: <strong>'+ai(used)+' نقطة</strong><br>الإجمالي النهائي: <strong>'+money(j.order.total)+' ج.م</strong><br>🎁 رصيد البونص المتبقي: <strong>'+ai(bal)+' نقطة</strong>';balance=bal;pointsEnabled=false;syncUI()}}catch{}}return res};
window.addEventListener('load',()=>setTimeout(loadPoints,900));window.addEventListener('pageshow',()=>setTimeout(loadPoints,500));
})();