(()=>{
const AUTH='https://qxwvuxkbcghbkztjrzon.supabase.co/auth/v1/token?grant_type=password';
const API='https://qxwvuxkbcghbkztjrzon.supabase.co/functions/v1/shop-api';
const KEY='sb_publishable_JI9lC4YPTCQ8CwMxzvHNIA_C24ULpWH';
const SKEY='alban_store_session';
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n||0).toFixed(2)+' ج';
const status={pending:'جديد',confirmed:'تم التأكيد',preparing:'جاري التجهيز',ready:'جاهز',assigned:'تم تعيين السائق',out_for_delivery:'خرج للتوصيل',delivered:'تم التسليم',cancelled:'ملغي',rejected:'مرفوض'};
let session=null,orders=[],drivers=[],timer=null,audioCtx=null,audioReady=false,ring=null,known=new Set();
function save(s){session=s;localStorage.setItem(SKEY,JSON.stringify(s));localStorage.setItem('alban_admin_session',JSON.stringify(s))}
function load(){try{session=JSON.parse(localStorage.getItem(SKEY)||localStorage.getItem('alban_admin_session')||'null')}catch{session=null}}
function login(){app.innerHTML=`<div class="store-wrap"><div class="store-box"><div class="store-logo">🥛 ألبان فلاحي</div><h2>برنامج المحل</h2><p class="muted">تسجيل دخول موظف/مدير الفرع</p><label>البريد الإلكتروني</label><input id="email" type="email" autocomplete="username"><label>كلمة المرور</label><input id="password" type="password" autocomplete="current-password"><button id="loginBtn" class="primary">دخول برنامج المحل</button><div id="msg" class="msg"></div></div></div>`;document.getElementById('loginBtn').onclick=doLogin;document.getElementById('password').onkeydown=e=>{if(e.key==='Enter')doLogin()}}
async function doLogin(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value,msg=document.getElementById('msg'),btn=document.getElementById('loginBtn');if(!email||!password){msg.textContent='أدخل البريد الإلكتروني وكلمة المرور';return}btn.disabled=true;btn.textContent='جارٍ الدخول...';msg.textContent='';try{const r=await fetch(AUTH,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw Error(d.error_description||d.msg||'البريد الإلكتروني أو كلمة المرور غير صحيحة');save({access_token:d.access_token,refresh_token:d.refresh_token,user:d.user});await boot()}catch(e){msg.textContent=e.message}finally{btn.disabled=false;btn.textContent='دخول برنامج المحل'}}
async function api(body){const r=await fetch(API,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||d.error||'تعذر الاتصال ببرنامج المحل');return d}
function beep(){if(!audioCtx||!audioReady)return;const now=audioCtx.currentTime;[0,.16,.32,.55,.71].forEach((at,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=i%2?900:1350;g.gain.setValueAtTime(.001,now+at);g.gain.exponentialRampToValueAtTime(.25,now+at+.02);g.gain.exponentialRampToValueAtTime(.001,now+at+.11);o.connect(g);g.connect(audioCtx.destination);o.start(now+at);o.stop(now+at+.12)})}
async function enableAudio(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;if(!audioCtx)audioCtx=new C;if(audioCtx.state==='suspended')await audioCtx.resume();audioReady=audioCtx.state==='running';if(audioReady){localStorage.setItem('alban_store_sound','1');document.getElementById('soundBtn')?.classList.add('ready');document.getElementById('soundBtn').textContent='🔊 الصوت مفعّل'}}catch{}}
function startRing(){if(ring||!audioReady)return;beep();ring=setInterval(beep,1500)}
function stopRing(){if(ring){clearInterval(ring);ring=null}}
async function setStatus(id,s){try{await api({action:'status',order_id:id,status:s});await refresh()}catch(e){alert(e.message)}}
async function refresh(){try{const data=await api({action:'orders'});orders=Array.isArray(data)?data:[];const pending=orders.filter(o=>o.status==='pending');const fresh=pending.filter(o=>!known.has(o.id));pending.forEach(o=>known.add(o.id));if(fresh.length){startRing();notify(fresh[0])}else if(!pending.length)stopRing();renderOrders()}catch(e){document.getElementById('error')?.replaceChildren(document.createTextNode(e.message))}}
function notify(o){document.title='🔔 طلب جديد | ألبان فلاحي';if('Notification' in window&&Notification.permission==='granted'){try{new Notification('🛵 طلب جديد — ألبان فلاحي',{body:`طلب #${o.order_number||o.id} — ${money(o.total)}`})}catch{}}}
function renderOrders(){const c=document.getElementById('orders');if(!c)return;c.innerHTML=orders.length?orders.map(o=>{const customer=o.customers||{},profile=customer.profiles||{},a=o.addresses||{},items=o.order_items||[];const next=o.status==='pending'?'confirmed':o.status==='confirmed'?'preparing':o.status==='preparing'?'ready':o.status==='ready'?'assigned':o.status==='assigned'?'out_for_delivery':null;return `<div class="order ${o.status==='pending'?'new':''}"><div class="order-head"><b>طلب #${esc(o.order_number||String(o.id).slice(0,8))}</b><span>${esc(status[o.status]||o.status)}</span></div><div>👤 ${esc(profile.full_name||'عميل')} — ${esc(customer.phone||'')}</div><div>📍 ${esc(a.address_text||'لا يوجد عنوان')} ${a.area?`— ${esc(a.area)}`:''}</div><div class="items">${items.map(i=>`<div>${esc(i.product_name_ar)} × ${esc(i.quantity)} — ${money(i.line_total)}</div>`).join('')||'لا توجد تفاصيل أصناف'}</div><div class="total">الإجمالي: ${money(o.total)}</div>${o.customer_notes?`<div>📝 ${esc(o.customer_notes)}</div>`:''}<div class="actions">${next?`<button onclick="window.storeStatus('${o.id}','${next}')">${next==='confirmed'?'✅ تأكيد الطلب':next==='preparing'?'👨‍🍳 بدء التجهيز':next==='ready'?'📦 الطلب جاهز':next==='assigned'?'🚗 تعيين السائق':'🛵 خرج للتوصيل'}</button>`:''}${o.status==='pending'?`<button class="danger" onclick="window.storeStatus('${o.id}','cancelled')">❌ رفض</button>`:''}</div></div>`}).join(''):'<div class="empty">لا توجد طلبات حاليًا.</div>'}
window.storeStatus=setStatus;
async function shell(){app.innerHTML=`<div class="store-app"><header><div><b>🥛 ألبان فلاحي</b><small>برنامج المحل</small></div><div class="head-actions"><button id="soundBtn" onclick="window.storeEnableAudio()">🔊 تفعيل الصوت</button><button onclick="window.storeRefresh()">↻ تحديث</button><button onclick="window.storeLogout()">خروج</button></div></header><main><div id="error" class="error"></div><div class="notice">طلبات الفرع تظهر هنا تلقائيًا. فعّل الصوت مرة واحدة بعد الدخول لسماع تنبيه الطلبات الجديدة.</div><div id="orders"></div></main></div>`;window.storeEnableAudio=enableAudio;window.storeRefresh=refresh;window.storeLogout=()=>{localStorage.removeItem(SKEY);localStorage.removeItem('alban_admin_session');location.reload()};document.body.addEventListener('click',()=>enableAudio(),{once:true});if('Notification' in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{});await refresh();timer=setInterval(refresh,5000)}
async function boot(){load();if(!session?.access_token){login();return}await shell()}
load();boot();
})();