import {useEffect,useMemo,useState} from 'react';
import {Check,Clock3,LogIn,LogOut,RefreshCw} from 'lucide-react';
import {supabase} from '../lib/supabase';
const statusAr:Record<string,string>={present:'حاضر',late:'متأخر',absent:'غائب',leave:'إجازة',rest:'راحة',sick_leave:'إجازة مرضية',missing_checkout:'لم يسجل انصراف'};
const cairoDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());
export default function Attendance(){
 const[profile,setProfile]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[employees,setEmployees]=useState<any[]>([]),[date,setDate]=useState(cairoDate()),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function load(){if(!supabase)return;setLoading(true);setError('');const{data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const{data:p,error:pe}=await supabase.from('hr_v2_accounts').select('id,full_name,role,employee_id,is_active').eq('id',user.id).maybeSingle();if(pe||!p){setError('تعذر تحميل الحساب');setLoading(false);return}setProfile(p);if(p.role==='employee'){const{data}=await supabase.from('hr_v2_attendance').select('*').eq('employee_id',p.employee_id).eq('work_date',date).maybeSingle();setRows(data?[data]:[])}else{const[{data:a},{data:e}]=await Promise.all([supabase.from('hr_v2_attendance').select('*').eq('work_date',date),supabase.from('hr_v2_employees').select('id,employee_no,full_name_ar,position,branch_id,max_daily_paid_hours,daily_work_hours').eq('status','active').order('full_name_ar')]);setRows(a||[]);setEmployees(e||[])}setLoading(false)}
 useEffect(()=>{load()},[date]);
 const byEmployee=useMemo(()=>Object.fromEntries(rows.map(r=>[r.employee_id,r])),[rows]);
 async function checkIn(id:string){if(!supabase)return;setBusy(id+'-in');setError('');const{error:e}=await supabase.from('hr_v2_attendance').insert({employee_id:id,work_date:date,check_in:new Date().toISOString(),check_out:null,notes:null});if(e)setError(e.code==='23505'?'تم تسجيل حضور الموظف بالفعل':e.message);await load();setBusy('')}
 async function checkOut(r:any){if(!supabase)return;setBusy(r.id+'-out');setError('');const{error:e}=await supabase.from('hr_v2_attendance').update({check_out:new Date().toISOString()}).eq('id',r.id);if(e)setError(e.message);await load();setBusy('')}
 async function markStatus(employeeId:string,status:string){if(!supabase)return;setBusy(employeeId+'-status');setError('');const existing=byEmployee[employeeId];const payload:any={status};if(status==='absent'||status==='leave'||status==='rest'||status==='sick_leave'){payload.check_in=null;payload.check_out=null;payload.approved_overtime_minutes=0;payload.approved_by=null;payload.approved_at=null}let e:any;if(existing)e=(await supabase.from('hr_v2_attendance').update(payload).eq('id',existing.id)).error;else e=(await supabase.from('hr_v2_attendance').insert({employee_id:employeeId,work_date:date,...payload,notes:null})).error;if(e)setError(e.message);await load();setBusy('')}
 async function approveExtra(r:any){if(!supabase)return;const extra=Math.max(0,Number(r.overtime_minutes||0));if(extra<=0)return;setBusy(r.id+'-ot');const{data:{user}}=await supabase.auth.getUser();const{error:e}=await supabase.from('hr_v2_attendance').update({approved_overtime_minutes:extra,approved_by:user?.id,approved_at:new Date().toISOString()}).eq('id',r.id);if(e)setError(e.message);await load();setBusy('')}
 if(loading)return <div className="panel"><div className="empty">جاري تحميل الحضور...</div></div>;
 if(profile?.role==='employee'){const today=rows[0];return <><div className="page-head"><div><h2>الحضور والانصراف</h2><p>سجل حضورك وانصرافك.</p></div><button className="secondary" onClick={load}><RefreshCw size={17}/>تحديث</button></div><div className="panel attendance-card"><div className="attendance-icon"><Clock3 size={32}/></div><h3>{profile.full_name}</h3><p className="muted">{date}</p><div className="attendance-times"><div><span>الحضور</span><b>{today?.check_in?new Date(today.check_in).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'}):'—'}</b></div><div><span>الانصراف</span><b>{today?.check_out?new Date(today.check_out).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'}):'—'}</b></div><div><span>الساعات المدفوعة</span><b>{today?((Number(today.work_minutes||0)/60).toFixed(2)):'0'} ساعة</b></div></div>{date===cairoDate()&&!today&&<button className="primary big-action" disabled={!!busy} onClick={()=>checkIn(profile.employee_id)}><LogIn size={19}/>تسجيل الحضور</button>}{date===cairoDate()&&today&&!today.check_out&&today.status!=='leave'&&today.status!=='rest'&&today.status!=='sick_leave'&&<button className="primary big-action" disabled={!!busy} onClick={()=>checkOut(today)}><LogOut size={19}/>تسجيل الانصراف</button>}{today?.check_out&&<div className="success">تم تسجيل اليوم — الساعات المدفوعة لا تتجاوز الحد المحدد.</div>}{today?.status&&<div className="hint">الحالة: {statusAr[today.status]||today.status}</div>}{error&&<div className="error">{error}</div>}</div></>}
 return <><div className="page-head"><div><h2>الحضور والانصراف</h2><p>شاشة المحاسب اليومية — تسجيل جميع الموظفين ومراجعة الساعات والإضافي.</p></div><div style={{display:'flex',gap:8,alignItems:'center'}}><input type="date" value={date} onChange={e=>setDate(e.target.value)} /><button className="secondary" onClick={load}><RefreshCw size={17}/>تحديث</button></div></div><div className="stats-grid"><div className="stat"><span>إجمالي الموظفين</span><strong>{employees.length}</strong></div><div className="stat"><span>حاضر</span><strong>{rows.filter(r=>r.check_in).length}</strong></div><div className="stat"><span>لم يسجل حضور</span><strong>{Math.max(0,employees.length-rows.filter(r=>r.check_in).length)}</strong></div><div className="stat"><span>إضافي بانتظار الاعتماد</span><strong>{rows.filter(r=>Number(r.overtime_minutes||0)>Number(r.approved_overtime_minutes||0)).length}</strong></div></div><div className="panel table-wrap"><table><thead><tr><th>الموظف</th><th>الوظيفة</th><th>الحضور</th><th>الانصراف</th><th>الساعات المدفوعة</th><th>إضافي فعلي</th><th>إضافي معتمد</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{employees.map(e=>{const r=byEmployee[e.id];return <tr key={e.id}><td>{e.full_name_ar}</td><td>{e.position||'—'}</td><td>{r?.check_in?new Date(r.check_in).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'}):'—'}</td><td>{r?.check_out?new Date(r.check_out).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'}):'—'}</td><td>{r?(Number(r.work_minutes||0)/60).toFixed(2):'0'} ساعة</td><td>{r?(Number(r.overtime_minutes||0)/60).toFixed(2):'0'} ساعة</td><td>{r?(Number(r.approved_overtime_minutes||0)/60).toFixed(2):'0'} ساعة</td><td><select value={r?.status||'absent'} onChange={x=>markStatus(e.id,x.target.value)} disabled={!!busy}><option value="present">حاضر</option><option value="late">متأخر</option><option value="absent">غائب</option><option value="leave">إجازة</option><option value="rest">راحة</option><option value="sick_leave">إجازة مرضية</option><option value="missing_checkout">لم يسجل انصراف</option></select></td><td>{!r&&<button className="icon-btn" disabled={!!busy} onClick={()=>checkIn(e.id)} title="تسجيل حضور"><LogIn size={17}/></button>}{r&&!r.check_out&&!['leave','rest','sick_leave','absent'].includes(r.status)&&<button className="icon-btn" disabled={!!busy} onClick={()=>checkOut(r)} title="تسجيل انصراف"><LogOut size={17}/></button>}{r&&Number(r.overtime_minutes||0)>Number(r.approved_overtime_minutes||0)&&<button className="icon-btn" disabled={!!busy} onClick={()=>approveExtra(r)} title="اعتماد الإضافي"><Check size={17}/></button>}</td></tr>})}</tbody></table>{error&&<div className="error" style={{margin:12}}>{error}</div>}</div></>;
}
