import {useEffect,useState} from 'react';
import {Clock3,WalletCards,ReceiptText,Timer,Users,Building2,AlertTriangle,Truck} from 'lucide-react';
import {supabase} from '../lib/supabase';
import type {Profile} from '../types';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());
export default function Dashboard({profile}:{profile:Profile}){
 const[s,setS]=useState<any>({employees:0,active:0,branches:0,attendance:0,missing:0,pendingOT:0,pendingMoney:0,payroll:0,deliveryHours:0});
 useEffect(()=>{(async()=>{if(!supabase)return;if(profile.role==='employee'){const [{data:a},{data:o},{data:m},{data:p}]=await Promise.all([supabase.from('hr_v2_attendance').select('*').eq('employee_id',profile.employee_id).order('work_date',{ascending:false}).limit(1),supabase.from('hr_v2_overtime').select('*').eq('employee_id',profile.employee_id).order('work_date',{ascending:false}).limit(1),supabase.from('hr_v2_money_transactions').select('*').eq('employee_id',profile.employee_id).order('transaction_date',{ascending:false}).limit(1),supabase.from('hr_v2_payroll').select('*').eq('employee_id',profile.employee_id).order('period_start',{ascending:false}).limit(1)]);setS((x:any)=>({...x,attendance:a?.[0]?.work_date?1:0,overtime:Number(o?.[0]?.amount||0),advances:Number(m?.[0]?.amount||0),payroll:Number(p?.[0]?.net_salary||0)}));return}
 const d=today();const[{count:employees},{count:active},{count:branches},{data:a},{data:o},{data:m},{data:del}]=await Promise.all([supabase.from('hr_v2_employees').select('*',{count:'exact',head:true}),supabase.from('hr_v2_employees').select('*',{count:'exact',head:true}).eq('status','active'),supabase.from('hr_v2_branches').select('*',{count:'exact',head:true}).eq('is_active',true),supabase.from('hr_v2_attendance').select('employee_id,check_in,check_out').eq('work_date',d),supabase.from('hr_v2_overtime').select('id').eq('approval_status','pending'),supabase.from('hr_v2_money_transactions').select('id').eq('approval_status','pending'),supabase.from('hr_v2_employees').select('id').eq('is_delivery',true).eq('status','active')]);let deliveryHours=0;if(del?.length){const ids=del.map(x=>x.id);const{data:da}=await supabase.from('hr_v2_attendance').select('work_minutes').in('employee_id',ids).eq('work_date',d);deliveryHours=(da||[]).reduce((n,x)=>n+Number(x.work_minutes||0),0)/60}setS({employees:employees||0,active:active||0,branches:branches||0,attendance:(a||[]).filter(x=>x.check_in).length,missing:(a||[]).filter(x=>x.check_in&&!x.check_out).length,pendingOT:o?.length||0,pendingMoney:m?.length||0,deliveryHours});})()},[profile]);
 if(profile.role==='employee')return <><div className="page-head"><div><h2>الرئيسية</h2><p>أهلاً {profile.full_name} — حسابك الوظيفي.</p></div></div><div className="stats-grid"><div className="stat-card"><Clock3 size={20}/><span>آخر حضور</span><strong>{s.attendance?'مسجل':'لا يوجد'}</strong></div><div className="stat-card"><Timer size={20}/><span>آخر إضافي</span><strong>{Number(s.overtime||0).toLocaleString('ar-EG')} ج.م</strong></div><div className="stat-card"><WalletCards size={20}/><span>آخر سلفة/خصم</span><strong>{Number(s.advances||0).toLocaleString('ar-EG')} ج.م</strong></div><div className="stat-card"><ReceiptText size={20}/><span>آخر صافي راتب</span><strong>{Number(s.payroll||0).toLocaleString('ar-EG')} ج.م</strong></div></div></>;
 return <><div className="page-head"><div><h2>لوحة التحكم</h2><p>إدارة ألبان فلاحي — نظرة تشغيلية سريعة.</p></div></div><div className="stats-grid"><div className="stat-card"><Users size={20}/><span>إجمالي الموظفين</span><strong>{s.employees}</strong></div><div className="stat-card"><Users size={20}/><span>الموظفون النشطون</span><strong>{s.active}</strong></div><div className="stat-card"><Building2 size={20}/><span>الفروع النشطة</span><strong>{s.branches}</strong></div><div className="stat-card"><Clock3 size={20}/><span>حضور اليوم</span><strong>{s.attendance}</strong></div><div className="stat-card"><AlertTriangle size={20}/><span>بدون انصراف</span><strong>{s.missing}</strong></div><div className="stat-card"><Timer size={20}/><span>طلبات إضافي معلقة</span><strong>{s.pendingOT}</strong></div><div className="stat-card"><WalletCards size={20}/><span>حركات مالية معلقة</span><strong>{s.pendingMoney}</strong></div><div className="stat-card"><Truck size={20}/><span>ساعات الدليفري اليوم</span><strong>{Number(s.deliveryHours||0).toFixed(2)} ساعة</strong></div></div><div className="report-grid"><div className="report-card"><h3>المتابعة اليومية</h3><p>من هنا تتابع الحضور، الغياب، التأخير والانصراف الناقص أولاً بأول.</p></div><div className="report-card"><h3>الموافقات</h3><p>راجع الإضافي والسلف والخصومات والمكافآت قبل إدخالها في مسير الراتب.</p></div><div className="report-card"><h3>الدليفري</h3><p>ساعات الدليفري تظهر للمحاسب، والحساب الأسبوعي من السبت إلى الجمعة.</p></div><div className="report-card"><h3>الرواتب</h3><p>بعد اعتماد الحضور والحركات، احسب المسير وأصدر كشف كل موظف بشكل منفصل.</p></div></div></>;
}
