import {useEffect,useMemo,useState} from 'react';
import {Check,Edit3,Search,Trash2,X,RefreshCw} from 'lucide-react';
import {supabase} from '../lib/supabase';

const cairoToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());
const timeValue=(v:string|null)=>v?new Date(v).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Africa/Cairo'}):'—';
const money=(n:any)=>Number(n||0).toLocaleString('ar-EG',{minimumFractionDigits:2,maximumFractionDigits:2})+' ج.م';
const hours=(n:any)=>(Number(n||0)/60).toFixed(2)+' س';
const dayKey=(date:string)=>{const d=new Date(`${date}T12:00:00`);return ['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][d.getDay()]};
const safeDate=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(d);
const monthAgo=()=>{const d=new Date();d.setDate(d.getDate()-30);return safeDate(d)};

export default function EmployeeReview(){
 const[employees,setEmployees]=useState<any[]>([]),[q,setQ]=useState(''),[selected,setSelected]=useState<any>(null),[start,setStart]=useState(monthAgo()),[end,setEnd]=useState(cairoToday()),[attendance,setAttendance]=useState<any[]>([]),[moneyRows,setMoneyRows]=useState<any[]>([]),[payroll,setPayroll]=useState<any[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[edit,setEdit]=useState<any>(null);
 async function loadEmployees(){if(!supabase)return;const{data,error}=await supabase.from('hr_v2_employees').select('*').order('full_name_ar');if(error)setError(error.message);else setEmployees(data||[])}
 useEffect(()=>{loadEmployees()},[]);
 async function loadEmployee(e:any){if(!supabase)return;setSelected(e);setLoading(true);setError('');const [a,m,p]=await Promise.all([
   supabase.from('hr_v2_attendance').select('*').eq('employee_id',e.id).gte('work_date',start).lte('work_date',end).order('work_date',{ascending:false}),
   supabase.from('hr_v2_money').select('*').eq('employee_id',e.id).gte('transaction_date',start).lte('transaction_date',end).order('transaction_date',{ascending:false}),
   supabase.from('hr_v2_payroll').select('*').eq('employee_id',e.id).order('period_end',{ascending:false})
 ]);if(a.error)setError(a.error.message);else setAttendance(a.data||[]);if(m.error)setError(m.error.message);else setMoneyRows(m.data||[]);if(p.error)setError(p.error.message);else setPayroll(p.data||[]);setLoading(false)}
 useEffect(()=>{if(selected)loadEmployee(selected)},[start,end]);
 const filtered=employees.filter(e=>String(e.full_name_ar||'').includes(q)||String(e.full_name_en||'').toLowerCase().includes(q.toLowerCase())||String(e.phone||'').includes(q));
 const stats=useMemo(()=>{const actual=attendance.reduce((s,r)=>s+Math.max(0,Number(r.work_minutes||0)),0);const ot=attendance.reduce((s,r)=>s+Math.max(0,Number(r.overtime_minutes||0)),0);const approved=attendance.reduce((s,r)=>s+Math.min(Math.max(0,Number(r.approved_overtime_minutes||0)),Math.max(0,Number(r.overtime_minutes||0))),0);const late=attendance.reduce((s,r)=>{const sch=r.work_date&&selected?.work_schedule?.[dayKey(r.work_date)];if(!r.check_in||!sch||sch.enabled===false||!sch.start)return s;const t=timeValue(r.check_in).split(':').map(Number);const a=sch.start.split(':').map(Number);return s+Math.max(0,(t[0]*60+t[1])-(a[0]*60+a[1]))},0);const pendingExtra=attendance.filter(r=>Number(r.overtime_minutes||0)>Number(r.approved_overtime_minutes||0)).length;const pendingException=attendance.filter(r=>r.schedule_exception_required&&!r.schedule_exception_approved).length;return{actual,ot,approved,late,pendingExtra,pendingException,days:attendance.length}},[attendance,selected]);
 const finance=useMemo(()=>{let adv=0,bonus=0,ded=0;moneyRows.forEach(r=>{const type=String(r.transaction_type||r.type||'').toLowerCase();const v=Number(r.amount||0);if(type.includes('advance')||type.includes('سلف'))adv+=v;else if(type.includes('bonus')||type.includes('مكاف'))bonus+=v;else if(type.includes('deduction')||type.includes('خصم'))ded+=v});return{adv,bonus,ded}},[moneyRows]);
 async function updateAttendance(r:any,patch:any){if(!supabase)return;setBusy(r.id);setError('');const{error:e}=await supabase.from('hr_v2_attendance').update(patch).eq('id',r.id);if(e)setError(e.message);else await loadEmployee(selected);setBusy('')}
 async function approve(r:any){if(r.schedule_exception_required&&!r.schedule_exception_approved){await updateAttendance(r,{schedule_exception_approved:true,schedule_exception_approved_at:new Date().toISOString()});return}if(Number(r.overtime_minutes||0)>Number(r.approved_overtime_minutes||0))await updateAttendance(r,{approved_overtime_minutes:Number(r.overtime_minutes||0),approved_at:new Date().toISOString()})}
 async function reject(r:any){if(!confirm('تأكيد رفض الساعات الإضافية/الحضور خارج الموعد لهذا اليوم؟'))return;const patch:any={approved_overtime_minutes:0,approved_by:null,approved_at:null};if(r.schedule_exception_required){patch.schedule_exception_approved=false;patch.schedule_exception_approved_by=null;patch.schedule_exception_approved_at=null}await updateAttendance(r,patch)}
 async function saveEdit(){if(!supabase||!edit)return;setBusy(edit.id);setError('');const ci=edit.in,co=edit.out;const iso=(d:string,t:string)=>t?new Date(`${d}T${t}:00`).toISOString():null;const x=await supabase.from('hr_v2_attendance').update({check_in:iso(edit.work_date,ci),check_out:iso(edit.work_date,co)}).eq('id',edit.id);if(x.error)setError(x.error.message);else{setEdit(null);await loadEmployee(selected)}setBusy('')}
 async function remove(r:any){if(!supabase||!confirm('حذف سجل الحضور لهذا اليوم؟'))return;setBusy(r.id);const x=await supabase.from('hr_v2_attendance').delete().eq('id',r.id);if(x.error)setError(x.error.message);else await loadEmployee(selected);setBusy('')}
 return <><div className="page-head"><div><h2>تقييم الموظفين</h2><p>ابحث عن الموظف وشاهد الحضور والساعات والتأخير والإضافي والحركات المالية.</p></div><button className="secondary" onClick={()=>selected?loadEmployee(selected):loadEmployees()}><RefreshCw size={17}/>تحديث</button></div>
 <div className="panel" style={{marginBottom:12}}><div className="search"><Search size={18}/><input placeholder="ابحث باسم الموظف..." value={q} onChange={e=>setQ(e.target.value)}/></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}>{filtered.map(e=><button key={e.id} className={selected?.id===e.id?'primary':'secondary'} onClick={()=>loadEmployee(e)}>{e.full_name_ar}</button>)}</div></div>
 {selected&&<><div className="panel" style={{marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'center'}}><div><h3 style={{margin:'0 0 5px'}}>{selected.full_name_ar}</h3><div className="muted">{selected.position||'—'} • {selected.phone||'بدون موبايل'} • {selected.is_delivery?'دليفري':'موظف'}</div></div><div style={{display:'flex',gap:8}}><label>من<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>إلى<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div></div></div>
 {error&&<div className="error">{error}</div>}
 <div className="stats-grid"><div className="stat"><span>أيام مسجلة</span><strong>{stats.days}</strong></div><div className="stat"><span>إجمالي ساعات الحضور</span><strong>{hours(stats.actual)}</strong></div><div className="stat"><span>التأخير</span><strong>{hours(stats.late)}</strong></div><div className="stat"><span>الإضافي</span><strong>{hours(stats.ot)}</strong></div><div className="stat"><span>إضافي معتمد</span><strong>{hours(stats.approved)}</strong></div><div className="stat"><span>معلّق للموافقة</span><strong>{stats.pendingExtra+stats.pendingException}</strong></div></div>
 <div className="panel table-wrap"><h3>سجل الحضور والانصراف</h3><table><thead><tr><th>التاريخ</th><th>الجدول</th><th>الحضور</th><th>الانصراف</th><th>الساعات</th><th>إضافي</th><th>التأخير</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{attendance.map(r=>{const sch=selected.work_schedule?.[dayKey(r.work_date)];const t=r.check_in?timeValue(r.check_in).split(':').map(Number):null;const a=sch?.start&&t?t[0]*60+t[1]-Number(sch.start.split(':')[0])*60-Number(sch.start.split(':')[1]):0;const pending=(Number(r.overtime_minutes||0)>Number(r.approved_overtime_minutes||0))||(r.schedule_exception_required&&!r.schedule_exception_approved);return <tr key={r.id}><td>{r.work_date}</td><td>{selected.is_delivery?'بدون جدول':sch?.enabled===false?'راحة':sch?`${sch.start} - ${sch.end}`:'—'}</td><td>{timeValue(r.check_in)}</td><td>{timeValue(r.check_out)}</td><td>{hours(r.work_minutes)}</td><td>{hours(r.overtime_minutes)} {Number(r.approved_overtime_minutes||0)>0&&<small>({hours(r.approved_overtime_minutes)} معتمد)</small>}</td><td>{a>0?hours(a):'—'}</td><td>{r.schedule_exception_required&&!r.schedule_exception_approved?'خارج الجدول — انتظار اعتماد':pending?'إضافي — انتظار اعتماد':r.status||'—'}</td><td><div style={{display:'flex',gap:4,flexWrap:'wrap'}}><button className="icon-btn" title="تعديل" onClick={()=>setEdit({id:r.id,work_date:r.work_date,in:r.check_in?timeValue(r.check_in):'',out:r.check_out?timeValue(r.check_out):''})}><Edit3 size={16}/></button>{pending&&<><button className="icon-btn" title="موافقة" onClick={()=>approve(r)} disabled={!!busy}><Check size={16}/></button><button className="icon-btn" title="رفض" onClick={()=>reject(r)} disabled={!!busy}><X size={16}/></button></>}<button className="icon-btn" title="حذف" onClick={()=>remove(r)} disabled={!!busy}><Trash2 size={16}/></button></div></td></tr>})}</tbody></table>{!attendance.length&&<div className="empty">لا يوجد حضور في الفترة المحددة.</div>}</div>
 <div className="panel"><h3>الحساب المالي</h3><div className="stats-grid"><div className="stat"><span>السلف</span><strong>{money(finance.adv)}</strong></div><div className="stat"><span>الخصومات</span><strong>{money(finance.ded)}</strong></div><div className="stat"><span>المكافآت</span><strong>{money(finance.bonus)}</strong></div><div className="stat"><span>قيمة الساعة / الأساسي</span><strong>{money(selected.base_salary)}</strong></div></div><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>النوع</th><th>القيمة</th><th>الحالة</th><th>البيان</th></tr></thead><tbody>{moneyRows.map(r=><tr key={r.id}><td>{r.transaction_date||'—'}</td><td>{r.transaction_type||r.type||'—'}</td><td>{money(r.amount)}</td><td>{r.approval_status||'نشطة'}</td><td>{r.notes||r.reason||'—'}</td></tr>)}</tbody></table></div></div>
 <div className="panel table-wrap"><h3>كشوف المرتب</h3><table><thead><tr><th>الفترة</th><th>الأساسي</th><th>إضافي</th><th>مكافآت</th><th>خصومات</th><th>سلف</th><th>الصافي</th><th>الحالة</th></tr></thead><tbody>{payroll.map(r=><tr key={r.id}><td>{r.period_start} → {r.period_end}</td><td>{money(r.base_salary)}</td><td>{money(r.overtime_total)}</td><td>{money(r.bonuses)}</td><td>{money(r.deductions)}</td><td>{money(r.advances)}</td><td><b>{money(r.net_salary)}</b></td><td>{r.status}</td></tr>)}</tbody></table>{!payroll.length&&<div className="empty">لا توجد كشوف محفوظة.</div>}</div>
 </>}
 {loading&&<div className="panel"><div className="empty">جاري تحميل ملف الموظف...</div></div>}
 {edit&&<div className="modal-backdrop"><div className="modal"><h3>تعديل حضور {selected?.full_name_ar}</h3><label>الدخول<input type="time" value={edit.in} onChange={e=>setEdit({...edit,in:e.target.value})}/></label><label>الانصراف<input type="time" value={edit.out} onChange={e=>setEdit({...edit,out:e.target.value})}/></label><div className="modal-actions"><button className="secondary" onClick={()=>setEdit(null)}>إلغاء</button><button className="primary" disabled={!!busy} onClick={saveEdit}>حفظ التعديل</button></div></div></div>}
 </>;
}
