import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Check,Edit3,RefreshCw,Search,X} from 'lucide-react';
import {supabase} from '../lib/supabase';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());
const monthAgo=()=>{const d=new Date();d.setDate(d.getDate()-30);return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(d)};
const money=(n:any)=>Number(n||0).toLocaleString('ar-EG',{minimumFractionDigits:2,maximumFractionDigits:2})+' ج.م';
const hours=(n:any)=>(Number(n||0)/60).toFixed(2)+' س';
const timeValue=(v:string|null)=>v?new Date(v).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Africa/Cairo'}):'—';
const dayKey=(date:string)=>{const d=new Date(`${date}T12:00:00`);return ['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][d.getDay()]};
const statusAr=(v:any)=>{const s=String(v||'').toLowerCase();return s==='present'?'حاضر':s==='absent'?'غائب':s==='late'?'متأخر':s==='approved'?'معتمد':s==='rejected'?'مرفوض':v||'—'};
export default function EmployeeReview(){
 const[employees,setEmployees]=useState<any[]>([]),[q,setQ]=useState(''),[selected,setSelected]=useState<any>(null),[start,setStart]=useState(monthAgo()),[end,setEnd]=useState(today()),[attendance,setAttendance]=useState<any[]>([]),[moneyRows,setMoneyRows]=useState<any[]>([]),[payroll,setPayroll]=useState<any[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[edit,setEdit]=useState<any>(null);
 async function loadEmployees(){const{data,error}=await supabase.from('hr_v2_employees').select('*').order('full_name_ar');if(error)setError(error.message);else setEmployees(data||[])}
 async function loadEmployee(e:any){setSelected(e);setLoading(true);setError('');const[a,m,p]=await Promise.all([supabase.from('hr_v2_attendance').select('*').eq('employee_id',e.id).gte('work_date',start).lte('work_date',end).order('work_date',{ascending:false}),supabase.from('hr_v2_money_transactions').select('*').eq('employee_id',e.id).gte('transaction_date',start).lte('transaction_date',end).order('transaction_date',{ascending:false}),supabase.from('hr_v2_payroll').select('*').eq('employee_id',e.id).order('period_end',{ascending:false})]);if(a.error)setError(a.error.message);else setAttendance(a.data||[]);if(m.error)setError(m.error.message);else setMoneyRows(m.data||[]);if(p.error)setError(p.error.message);else setPayroll(p.data||[]);setLoading(false)}
 useEffect(()=>{loadEmployees()},[]);useEffect(()=>{if(selected)loadEmployee(selected)},[start,end]);
 const filtered=employees.filter(e=>String(e.full_name_ar||'').includes(q)||String(e.full_name_en||'').toLowerCase().includes(q.toLowerCase())||String(e.phone||'').includes(q));
 const metrics=useMemo(()=>{let worked=0,late=0,ot=0,approvedOt=0,missing=0,pendingException=0,present=0;attendance.forEach(r=>{worked+=Math.max(0,Number(r.work_minutes||0));if(r.check_in)present++;if(r.check_in&&!r.check_out)missing++;ot+=Math.max(0,Number(r.overtime_minutes||0));approvedOt+=Math.min(Math.max(0,Number(r.approved_overtime_minutes||0)),Math.max(0,Number(r.overtime_minutes||0)));if(r.schedule_exception_required&&!r.schedule_exception_approved)pendingException++;const sch=selected?.work_schedule?.[dayKey(r.work_date)];if(r.check_in&&sch?.enabled!==false&&sch?.start){const t=timeValue(r.check_in).split(':').map(Number),a=sch.start.split(':').map(Number);late+=Math.max(0,t[0]*60+t[1]-a[0]*60-a[1])}});const absent=Math.max(0,attendance.length-present);const lateRate=present?Math.min(100,late/(present*60)*100):0;const missingRate=attendance.length?missing/attendance.length*100:0;const approvalRate=ot?approvedOt/ot*100:100;const score=Math.round(Math.max(0,100-lateRate*.45-missingRate*.3-(100-approvalRate)*.25));return{worked,late,ot,approvedOt,missing,pendingException,present,absent,lateRate,missingRate,approvalRate,score,label:score>=90?'ممتاز':score>=75?'جيد':score>=60?'يحتاج متابعة':'يحتاج تدخل'}},[attendance,selected]);
 const finance=useMemo(()=>moneyRows.reduce((x,r)=>{const t=String(r.type||'').toLowerCase(),v=Number(r.amount||0);if(t==='advance')x.adv+=v;else if(t==='bonus')x.bonus+=v;else if(t==='deduction')x.ded+=v;return x},{adv:0,bonus:0,ded:0}),[moneyRows]);
 const insight=useMemo(()=>{const a:string[]=[];if(metrics.score<75)a.push('مؤشر الالتزام أقل من المستوى المستهدف');if(metrics.lateRate>10)a.push('التأخير مرتفع ويحتاج متابعة');if(metrics.missing)a.push(`يوجد ${metrics.missing} سجل بدون انصراف`);if(metrics.pendingException)a.push(`يوجد ${metrics.pendingException} حضور خارج الموعد يحتاج اعتماد`);if(metrics.ot>metrics.approvedOt)a.push('يوجد إضافي غير معتمد');if(finance.ded>0)a.push(`خصومات بقيمة ${money(finance.ded)}`);if(!a.length)a.push('أداء مستقر ولا توجد إشارات خطر واضحة في الفترة');return a},[metrics,finance]);
 async function updateAttendance(r:any,patch:any){setBusy(r.id);setError('');const{error}=await supabase.from('hr_v2_attendance').update(patch).eq('id',r.id);if(error)setError(error.message);else await loadEmployee(selected);setBusy('')}
 async function approve(r:any){if(r.schedule_exception_required&&!r.schedule_exception_approved){await updateAttendance(r,{schedule_exception_approved:true,schedule_exception_approved_at:new Date().toISOString()});return}if(Number(r.overtime_minutes||0)>Number(r.approved_overtime_minutes||0))await updateAttendance(r,{approved_overtime_minutes:Number(r.overtime_minutes||0),approved_at:new Date().toISOString()})}
 async function reject(r:any){if(!confirm('تأكيد رفض الإضافي/الحضور خارج الموعد؟'))return;const patch:any={approved_overtime_minutes:0,approved_by:null,approved_at:null};if(r.schedule_exception_required){patch.schedule_exception_approved=false;patch.schedule_exception_approved_by=null;patch.schedule_exception_approved_at=null}await updateAttendance(r,patch)}
 async function saveEdit(){if(!edit)return;setBusy(edit.id);const iso=(d:string,t:string)=>t?new Date(`${d}T${t}:00`).toISOString():null;const{error}=await supabase.from('hr_v2_attendance').update({check_in:iso(edit.work_date,edit.in),check_out:iso(edit.work_date,edit.out)}).eq('id',edit.id);if(error)setError(error.message);else{setEdit(null);await loadEmployee(selected)}setBusy('')}
 return <><div className="page-head"><div><h2>تقييم الموظفين</h2><p>تحليل أداء الموظف واتخاذ قرار مبني على الحضور والانضباط والتكلفة.</p></div><button className="secondary" onClick={()=>selected?loadEmployee(selected):loadEmployees()} disabled={loading}><RefreshCw size={17}/> تحديث</button></div>
 <div className="panel" style={{marginBottom:12}}><div className="search"><Search size={18}/><input placeholder="ابحث باسم الموظف أو الموبايل..." value={q} onChange={e=>setQ(e.target.value)}/></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}>{filtered.map(e=><button key={e.id} className={selected?.id===e.id?'primary':'secondary'} onClick={()=>loadEmployee(e)}>{e.full_name_ar}</button>)}</div></div>
 {selected&&<><div className="panel" style={{marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'center'}}><div><h3 style={{margin:'0 0 5px'}}>{selected.full_name_ar}</h3><div className="muted">{selected.position||'—'} • {selected.phone||'بدون موبايل'} • {selected.is_delivery?'دليفري':'موظف'}</div></div><div style={{display:'flex',gap:8}}><label>من<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>إلى<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div></div></div>{error&&<div className="error">{error}</div>}
 <div className="report-grid" style={{marginBottom:12}}><div className="report-card" style={{gridColumn:'span 2'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><h3>⭐ مؤشر أداء الموظف</h3><p>مؤشر استرشادي مبني على بيانات الفترة المختارة.</p></div><strong style={{fontSize:32}}>{metrics.score}%</strong></div><div style={{marginTop:10,height:12,borderRadius:10,background:'#eee',overflow:'hidden'}}><div style={{width:`${metrics.score}%`,height:'100%',background:'currentColor'}}/></div><strong style={{display:'block',marginTop:8}}>{metrics.label}</strong></div><div className="report-card"><h3>🚦 قرار المتابعة</h3>{insight.slice(0,4).map((x,i)=><div key={i} style={{padding:'7px 0',borderBottom:'1px solid #eee'}}>{x}</div>)}</div></div>
 <div className="stats-grid"><div className="stat"><span>أيام حضور</span><strong>{metrics.present}</strong></div><div className="stat"><span>ساعات الحضور</span><strong>{hours(metrics.worked)}</strong></div><div className="stat"><span>التأخير</span><strong>{hours(metrics.late)}</strong></div><div className="stat"><span>نسبة الالتزام</span><strong>{metrics.score}%</strong></div><div className="stat"><span>الإضافي</span><strong>{hours(metrics.ot)}</strong></div><div className="stat"><span>الإضافي المعتمد</span><strong>{hours(metrics.approvedOt)}</strong></div><div className="stat"><span>بدون انصراف</span><strong>{metrics.missing}</strong></div><div className="stat"><span>خارج الموعد المعلق</span><strong>{metrics.pendingException}</strong></div></div>
 <div className="panel"><h3>💰 تكلفة الموظف والحركات</h3><div className="stats-grid"><div className="stat"><span>الراتب الأساسي</span><strong>{money(selected.base_salary)}</strong></div><div className="stat"><span>إضافي معتمد</span><strong>{money(metrics.approvedOt/60*Number(selected.overtime_rate||0))}</strong></div><div className="stat"><span>سلف</span><strong>{money(finance.adv)}</strong></div><div className="stat"><span>خصومات</span><strong>{money(finance.ded)}</strong></div><div className="stat"><span>مكافآت</span><strong>{money(finance.bonus)}</strong></div><div className="stat"><span>صافي تقديري</span><strong>{money(Number(selected.base_salary||0)+metrics.approvedOt/60*Number(selected.overtime_rate||0)+finance.bonus-finance.ded-finance.adv)}</strong></div></div></div>
 <div className="panel"><h3>🧠 ملخص المالك</h3><div style={{display:'grid',gap:8}}>{insight.map((x,i)=><div key={i} style={{display:'flex',gap:8,alignItems:'center'}}>{x.includes('مستقر')?<Check size={17}/>:<AlertTriangle size={17}/>}<span>{x}</span></div>)}</div></div>
 <div className="panel table-wrap"><h3>سجل الحضور والانصراف</h3><table><thead><tr><th>التاريخ</th><th>الجدول</th><th>الحضور</th><th>الانصراف</th><th>الساعات</th><th>إضافي</th><th>التأخير</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{attendance.map(r=>{const sch=selected.work_schedule?.[dayKey(r.work_date)],t=r.check_in?timeValue(r.check_in).split(':').map(Number):null,late=sch?.start&&t?Math.max(0,t[0]*60+t[1]-Number(sch.start.split(':')[0])*60-Number(sch.start.split(':')[1])):0,pending=Number(r.overtime_minutes||0)>Number(r.approved_overtime_minutes||0)||(r.schedule_exception_required&&!r.schedule_exception_approved);return <tr key={r.id}><td>{r.work_date}</td><td>{selected.is_delivery?'بدون جدول':sch?.enabled===false?'راحة':sch?`${sch.start} - ${sch.end}`:'—'}</td><td>{timeValue(r.check_in)}</td><td>{timeValue(r.check_out)}</td><td>{hours(r.work_minutes)}</td><td>{hours(r.overtime_minutes)} {Number(r.approved_overtime_minutes||0)>0&&<small>({hours(r.approved_overtime_minutes)} معتمد)</small>}</td><td>{late?hours(late):'—'}</td><td>{r.schedule_exception_required&&!r.schedule_exception_approved?'خارج الجدول — انتظار اعتماد':pending?'إضافي — انتظار اعتماد':statusAr(r.status)}</td><td><div style={{display:'flex',gap:4}}><button className="icon-btn" title="تعديل" onClick={()=>setEdit({id:r.id,work_date:r.work_date,in:r.check_in?timeValue(r.check_in):'',out:r.check_out?timeValue(r.check_out):''})}><Edit3 size={16}/></button>{pending&&<><button className="icon-btn" title="موافقة" onClick={()=>approve(r)} disabled={!!busy}><Check size={16}/></button><button className="icon-btn" title="رفض" onClick={()=>reject(r)} disabled={!!busy}><X size={16}/></button></>}</div></td></tr>})}</tbody></table>{!attendance.length&&<div className="empty">لا يوجد حضور في الفترة المحددة.</div>}</div>
 <div className="panel table-wrap"><h3>الحركات المالية</h3><table><thead><tr><th>التاريخ</th><th>النوع</th><th>القيمة</th><th>الحالة</th><th>البيان</th></tr></thead><tbody>{moneyRows.map(r=><tr key={r.id}><td>{r.transaction_date||'—'}</td><td>{r.type==='advance'?'سلفة':r.type==='deduction'?'خصم':r.type==='bonus'?'مكافأة':r.type||'—'}</td><td>{money(r.amount)}</td><td>{r.approval_status==='rejected'?'مرفوضة':r.approval_status==='pending'?'في انتظار الاعتماد':'مفعّلة'}</td><td>{r.notes||r.reason||'—'}</td></tr>)}</tbody></table>{!moneyRows.length&&<div className="empty">لا توجد حركات مالية في الفترة المحددة.</div>}</div>
 <div className="panel table-wrap"><h3>كشوف المرتب المحفوظة</h3><table><thead><tr><th>الفترة</th><th>الأساسي</th><th>إضافي</th><th>مكافآت</th><th>خصومات</th><th>سلف</th><th>الصافي</th><th>الحالة</th></tr></thead><tbody>{payroll.map(r=><tr key={r.id}><td>{r.period_start} → {r.period_end}</td><td>{money(r.base_salary)}</td><td>{money(r.overtime_total)}</td><td>{money(r.bonuses)}</td><td>{money(r.deductions)}</td><td>{money(r.advances)}</td><td><b>{money(r.net_salary)}</b></td><td>{statusAr(r.status)}</td></tr>)}</tbody></table>{!payroll.length&&<div className="empty">لا توجد كشوف محفوظة.</div>}</div></>}
 {edit&&<div className="modal-backdrop"><div className="modal"><h3>تعديل الحضور — {edit.work_date}</h3><div className="form-grid"><label>الحضور<input type="time" value={edit.in} onChange={e=>setEdit({...edit,in:e.target.value})}/></label><label>الانصراف<input type="time" value={edit.out} onChange={e=>setEdit({...edit,out:e.target.value})}/></label></div><div style={{display:'flex',gap:8,justifyContent:'flex-end',marginTop:16}}><button className="secondary" onClick={()=>setEdit(null)}>إلغاء</button><button className="primary" onClick={saveEdit} disabled={!!busy}>حفظ</button></div></div></div>}
 </>;
}