import {useEffect,useState} from 'react';
import {Eye,LockKeyhole,LogOut} from 'lucide-react';
import type {Profile} from '../types';
import {supabase} from '../lib/supabase';
const money=(n:any)=>Number(n||0).toLocaleString('ar-EG',{minimumFractionDigits:2,maximumFractionDigits:2})+' ج.م';
const hours=(n:any)=>(Number(n||0)/60).toFixed(2)+' س';
const timeValue=(v:string|null)=>v?new Date(v).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Africa/Cairo'}):'—';
const statusAr=(v:any)=>{const s=String(v||'').toLowerCase();return s==='present'?'حاضر':s==='absent'?'غائب':s==='late'?'متأخر':s==='leave'?'إجازة':s==='rest'?'راحة':s==='sick_leave'?'إجازة مرضية':s==='missing_checkout'?'بدون انصراف':s==='no_record'?'لا يوجد تسجيل حضور أو انصراف':v||'—'};
export default function EmployeePortal({profile}:{profile:Profile}){
 const[periods,setPeriods]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[statement,setStatement]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[changing,setChanging]=useState(false),[changeError,setChangeError]=useState('');
 async function loadPeriods(){setLoading(true);const{data,error}=await supabase.rpc('hr_v2_get_my_employee_periods');if(error){setError(error.message);setLoading(false);return}const list=Array.isArray(data)?data:[];setPeriods(list);if(list[0])await openStatement(list[0].id,list[0]);else setLoading(false)}
 async function openStatement(id:string,period?:any){setError('');const{data,error}=await supabase.rpc('hr_v2_get_my_employee_statement',{p_payroll_id:id});if(error)setError(error.message);else{setStatement(data);setSelected(period||periods.find(p=>p.id===id)||null)}setLoading(false)}
 useEffect(()=>{loadPeriods()},[]);
 async function changePassword(){setChangeError('');if(newPassword.length<6)return setChangeError('كلمة المرور الجديدة يجب ألا تقل عن 6 أحرف.');if(newPassword!==confirmPassword)return setChangeError('كلمتا المرور غير متطابقتين.');setChanging(true);const{error}=await supabase.auth.updateUser({password:newPassword});if(error){setChangeError(error.message);setChanging(false);return}const r=await supabase.rpc('hr_v2_complete_employee_password_change');if(r.error){setChangeError(r.error.message);setChanging(false);return}window.location.reload()}
 async function logout(){await supabase.auth.signOut();window.location.href='/login'}
 if(profile.must_change_password)return <main className="login-page"><section className="login-card"><div className="login-brand"><LockKeyhole size={36}/><div><h1>تغيير كلمة المرور</h1><p>{profile.full_name}</p></div></div><p className="muted">هذه أول مرة تدخل فيها النظام. يجب تغيير كلمة المرور الأولى قبل مشاهدة الكشف.</p><label>كلمة المرور الجديدة<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoFocus/></label><label>تأكيد كلمة المرور<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label>{changeError&&<div className="error">{changeError}</div>}<button className="primary full" onClick={changePassword} disabled={changing}>{changing?'جاري الحفظ...':'حفظ كلمة المرور'}</button><button className="secondary full" onClick={logout}>تسجيل الخروج</button></section></main>;
 return <main style={{minHeight:'100vh',background:'#f6f7f9',padding:'24px'}} dir="rtl"><div style={{maxWidth:1100,margin:'0 auto'}}><div className="panel" style={{marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 5px'}}>كشف الموظف</h2><div className="muted">{profile.full_name}</div></div><button className="secondary" onClick={logout}><LogOut size={17}/>تسجيل الخروج</button></div></div>
 {periods.length>0&&<div className="panel" style={{marginBottom:14}}><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{periods.map(p=><button key={p.id} className={selected?.id===p.id?'primary':'secondary'} onClick={()=>openStatement(p.id)}>من {p.period_start} إلى {p.period_end}</button>)}</div></div>}
 {error&&<div className="error" style={{marginBottom:12}}>{error}</div>}{loading?<div className="panel">جاري تحميل الكشف...</div>:!statement?<div className="panel" style={{textAlign:'center',padding:40}}>لا يوجد كشف معتمد نهائيًا متاح لك حتى الآن.</div>:<div className="panel">
 <div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',marginBottom:18}}><div><h2 style={{margin:0}}>كشف الحضور والانصراف والمرتبات</h2><div className="muted">ألبان فلاحي - إدارة الموارد البشرية</div></div><div style={{textAlign:'left'}}><div>الفترة: <strong>{statement.period?.start} — {statement.period?.end}</strong></div></div></div>
 <div style={{display:'flex',gap:18,flexWrap:'wrap',marginBottom:18}}><div>الموظف: <strong>{statement.employee?.full_name_ar}</strong></div><div>الوظيفة: <strong>{statement.employee?.position||'—'}</strong></div></div>
 <h3>تقييم الالتزام خلال الفترة</h3><div className="report-card" style={{textAlign:'center',fontSize:28,fontWeight:700}}>⭐ تقييم الالتزام: {statement.commitment_score||0}%</div><div className="note">يُحسب من الالتزام بالحضور في الأيام المجدولة، الالتزام بموعد الحضور، وتسجيل الانصراف. لا يدخل العمل الإضافي في التقييم.</div>
 <h3>إجمالي المستحق</h3><div className="report-card" style={{textAlign:"center",fontSize:28,fontWeight:700}}>💰 إجمالي المستحق: {money(Number(statement.payroll?.base_salary||0)+Number(statement.payroll?.overtime_total||0)+Number(statement.payroll?.bonuses||0))}</div><div className="note">المرتب + الإضافي المعتمد + المكافآت المعتمدة فقط، بدون خصومات أو سلف.</div>
 <h3>الساعات المحتسبة للمرتب</h3><div className="report-card" style={{textAlign:'center',fontSize:28,fontWeight:700}}>الساعات المحتسبة للمرتب: {hours(statement.total_paid_minutes)}</div><div className="note">إجمالي الساعات المدفوعة طبقًا لحساب المرتب الرسمي للفترة المحددة.</div>
 <h3>كشف الحضور والانصراف</h3><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>الجدول</th><th>الحضور</th><th>الانصراف</th><th>ساعات الحضور</th><th>الحالة</th></tr></thead><tbody>{(statement.attendance||[]).map((r:any)=><tr key={r.work_date}><td>{r.work_date}</td><td>{r.schedule||'—'}</td><td>{r.check_in?timeValue(r.check_in):r.status==='no_record'?'لا يوجد تسجيل': '—'}</td><td>{r.check_out?timeValue(r.check_out):r.status==='no_record'?'لا يوجد تسجيل':'—'}</td><td>{r.status==='no_record'?'—':hours(r.work_minutes)}</td><td>{statusAr(r.status)}</td></tr>)}</tbody></table></div>
 <h3>الحركات المالية المعتمدة</h3><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>النوع</th><th>القيمة</th><th>البيان</th></tr></thead><tbody>{(statement.money||[]).length?(statement.money||[]).map((r:any)=><tr key={r.transaction_date+'-'+r.type+'-'+r.amount}><td>{r.transaction_date}</td><td>{r.type==='bonus'?'مكافأة':r.type==='deduction'?'خصم':r.type==='advance'?'سلفة':r.type||'حركة'}</td><td>{money(r.amount)}</td><td>{r.notes||r.reason||'—'}</td></tr>):<tr><td colSpan={4}>لا توجد حركات مالية معتمدة في الفترة</td></tr>}</tbody></table></div>
 <div className="stats-grid" style={{marginTop:12}}><div className="stat"><span>إجمالي المكافآت</span><strong>{money(statement.payroll?.bonuses)}</strong></div><div className="stat"><span>إجمالي الخصومات</span><strong>{money(statement.payroll?.deductions)}</strong></div><div className="stat"><span>إجمالي السلف</span><strong>{money(statement.payroll?.advances)}</strong></div><div className="stat"><span>الخصم من الحضور/التأخير</span><strong>{money(Number(statement.payroll?.attendance_deduction||0)+Number(statement.payroll?.lateness_deduction||0))}</strong></div></div>
 <div className="net" style={{marginTop:14}}>صافي المرتب المستحق: {money(statement.payroll?.net_salary)}</div>
 </div>}</div></main>;
}