import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowUp,RefreshCw,Search,UserRoundSearch,X} from 'lucide-react';
import {supabase} from '../lib/supabase';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());
const monthAgo=()=>{const d=new Date();d.setDate(d.getDate()-30);return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(d)};
const hours=(n:number)=>(n/60).toFixed(1)+' س';
const dayKey=(date:string)=>{const d=new Date(`${date}T12:00:00`);return ['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][d.getDay()]};
const timeValue=(v:string|null)=>v?new Date(v).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Africa/Cairo'}):'';
export default function EmployeeRanking(){
 const[from,setFrom]=useState(monthAgo()),[to,setTo]=useState(today()),[employees,setEmployees]=useState<any[]>([]),[attendance,setAttendance]=useState<any[]>([]),[branches,setBranches]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[compareA,setCompareA]=useState(''),[compareB,setCompareB]=useState('');
 async function load(){setLoading(true);setError('');const[e,a,b]=await Promise.all([supabase.from('hr_v2_employees').select('*').eq('status','active').order('full_name_ar'),supabase.from('hr_v2_attendance').select('*').gte('work_date',from).lte('work_date',to),supabase.from('hr_v2_branches').select('id,name')]);if(e.error||a.error||b.error)setError(e.error?.message||a.error?.message||b.error?.message||'تعذر تحميل التحليل');else{setEmployees(e.data||[]);setAttendance(a.data||[]);setBranches(b.data||[])}setLoading(false)}
 useEffect(()=>{load()},[from,to]);
 const rows=useMemo(()=>{const bm=new Map(branches.map(b=>[b.id,b.name]));return employees.map(e=>{const rs=attendance.filter(a=>a.employee_id===e.id);let worked=0,late=0,ot=0,approvedOt=0,missing=0,pending=0,present=0;rs.forEach(r=>{worked+=Math.max(0,Number(r.work_minutes||0));if(r.check_in)present++;if(r.check_in&&!r.check_out)missing++;ot+=Math.max(0,Number(r.overtime_minutes||0));approvedOt+=Math.min(Math.max(0,Number(r.approved_overtime_minutes||0)),Math.max(0,Number(r.overtime_minutes||0)));if(r.schedule_exception_required&&!r.schedule_exception_approved)pending++;const sch=e.work_schedule?.[dayKey(r.work_date)];if(r.check_in&&sch?.enabled!==false&&sch?.start){const t=timeValue(r.check_in).split(':').map(Number),s=sch.start.split(':').map(Number);late+=Math.max(0,t[0]*60+t[1]-s[0]*60-s[1])}});const lateRate=present?Math.min(100,late/(present*60)*100):0;const missingRate=rs.length?missing/rs.length*100:0;const approval=ot?approvedOt/ot*100:100;const score=Math.round(Math.max(0,100-lateRate*.45-missingRate*.3-(100-approval)*.25));return{...e,branchName:bm.get(e.branch_id)||'بدون فرع',worked,late,ot,approvedOt,missing,pending,present,score,label:score>=90?'ممتاز':score>=75?'جيد':score>=60?'يحتاج متابعة':'يحتاج تدخل'}}).sort((a,b)=>b.score-a.score)},[employees,attendance,branches]);
 const filtered=rows.filter(r=>String(r.full_name_ar||'').includes(q)||String(r.position||'').includes(q)||String(r.branchName||'').includes(q));
 const best=rows[0],worst=rows.length?rows[rows.length-1]:null,avg=rows.length?Math.round(rows.reduce((n,r)=>n+r.score,0)/rows.length):0,need=rows.filter(r=>r.score<75).length;
 const a=rows.find(r=>r.id===compareA),b=rows.find(r=>r.id===compareB);
 const open=(id:string)=>{window.location.href=`/employee-review?employee=${id}`};
 const startCompare=(id:string)=>{if(!compareA)setCompareA(id);else if(id!==compareA)setCompareB(id)};
 const metrics=a&&b?[['التقييم',`${a.score}%`,`${b.score}%`,a.score-b.score],['الحضور',String(a.present),String(b.present),a.present-b.present],['ساعات العمل',hours(a.worked),hours(b.worked),a.worked-b.worked],['التأخير',hours(a.late),hours(b.late),b.late-a.late],['بدون انصراف',String(a.missing),String(b.missing),b.missing-a.missing],['الإضافي',hours(a.ot),hours(b.ot),a.ot-b.ot],['اعتماد الإضافي',`${a.ot?Math.round(a.approvedOt/a.ot*100):100}%`,`${b.ot?Math.round(b.approvedOt/b.ot*100):100}%`,(a.ot?Math.round(a.approvedOt/a.ot*100):100)-(b.ot?Math.round(b.approvedOt/b.ot*100):100)],['خارج الموعد يحتاج اعتماد',String(a.pending),String(b.pending),b.pending-a.pending]]:[];
 return <div dir="rtl"><div className="page-head"><div><h2>ترتيب وتحليل الموظفين</h2><p>مقارنة جماعية وقرار أدق للمالك خلال الفترة المختارة.</p></div><button className="secondary" onClick={load} disabled={loading}><RefreshCw size={17}/> {loading?'جاري التحميل':'تحديث'}</button></div>
 <div className="panel" style={{marginBottom:16}}><div style={{display:'flex',gap:12,alignItems:'end',flexWrap:'wrap'}}><label>من<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>إلى<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><div className="search" style={{flex:1,minWidth:220}}><Search size={18}/><input placeholder="بحث بالاسم أو الوظيفة أو الفرع" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div style={{marginTop:10,fontSize:13}}><b>المقارنة:</b> اختر موظفًا أولًا ثم ثانيًا من الجدول لإظهار مقارنة تفصيلية.</div></div>
 {error&&<div className="error" style={{marginBottom:16}}>{error}</div>}
 <div className="stats-grid"><div className="stat-card"><UserRoundSearch size={20}/><span>موظفون نشطون</span><strong>{rows.length}</strong></div><div className="stat-card"><ArrowUp size={20}/><span>متوسط التقييم</span><strong>{avg}%</strong></div><div className="stat-card"><AlertTriangle size={20}/><span>يحتاجون متابعة</span><strong>{need}</strong></div><div className="stat-card"><span>🏆 أفضل موظف</span><strong>{best?.full_name_ar||'—'}</strong><small>{best?`${best.score}% — ${best.label}`:''}</small></div></div>
 {a&&b&&<div className="panel" style={{margin:'16px 0',border:'2px solid #ddd'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap'}}><div><h3 style={{margin:0}}>⚖️ مقارنة تفصيلية</h3><p style={{margin:'5px 0 0'}}>{a.full_name_ar} مقابل {b.full_name_ar}</p></div><button className="secondary" onClick={()=>{setCompareA('');setCompareB('')}}><X size={16}/> إلغاء المقارنة</button></div><div className="table-wrap" style={{marginTop:12}}><table><thead><tr><th>المؤشر</th><th>{a.full_name_ar}</th><th>{b.full_name_ar}</th><th>الأفضل</th></tr></thead><tbody>{metrics.map(m=><tr key={m[0]}><td><b>{m[0]}</b></td><td>{m[1]}</td><td>{m[2]}</td><td><b>{Number(m[3])>0?a.full_name_ar:Number(m[3])<0?b.full_name_ar:'تعادل'}</b></td></tr>)}</tbody></table></div><div style={{marginTop:12,display:'flex',gap:8,flexWrap:'wrap'}}><button className="primary" onClick={()=>open(a.id)}>فتح ملف {a.full_name_ar}</button><button className="secondary" onClick={()=>open(b.id)}>فتح ملف {b.full_name_ar}</button></div></div>}
 <div className="report-grid" style={{marginBottom:16}}>{best&&<div className="report-card"><h3>🥇 الأفضل</h3><strong style={{fontSize:23}}>{best.full_name_ar}</strong><p>{best.position||'—'} • {best.branchName}</p><strong>{best.score}%</strong><button className="primary" style={{width:'100%',marginTop:10}} onClick={()=>open(best.id)}>فتح الملف الكامل</button></div>}{worst&&<div className="report-card"><h3>🚨 الأكثر احتياجًا للمتابعة</h3><strong style={{fontSize:23}}>{worst.full_name_ar}</strong><p>{worst.position||'—'} • {worst.branchName}</p><strong>{worst.score}%</strong><button className="secondary" style={{width:'100%',marginTop:10}} onClick={()=>open(worst.id)}>فتح الملف الكامل</button></div>}</div>
 <div className="panel table-wrap"><table><thead><tr><th>#</th><th>الموظف</th><th>الفرع</th><th>الوظيفة</th><th>التقييم</th><th>الحضور</th><th>التأخير</th><th>بدون انصراف</th><th>الإضافي</th><th>اعتماد الإضافي</th><th>خارج الموعد</th><th>الإجراء</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r.id}><td>{i+1}</td><td><b>{r.full_name_ar}</b></td><td>{r.branchName}</td><td>{r.position||'—'}</td><td><b>{r.score}%</b><br/><small>{r.label}</small></td><td>{r.present}</td><td>{hours(r.late)}</td><td>{r.missing}</td><td>{hours(r.ot)}</td><td>{r.ot?Math.round(r.approvedOt/r.ot*100):100}%</td><td>{r.pending}</td><td style={{display:'flex',gap:5,flexWrap:'wrap'}}><button className="secondary" onClick={()=>startCompare(r.id)}>{compareA===r.id?'اختر الثاني':'قارن'}</button><button className="secondary" onClick={()=>open(r.id)}>التفاصيل</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">لا توجد بيانات مطابقة.</div>}</div></div>
}