import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowDown,ArrowUp,RefreshCw,Search,UserRoundSearch,X} from 'lucide-react';
import {supabase} from '../lib/supabase';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());
const monthAgo=()=>{const d=new Date();d.setDate(d.getDate()-30);return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(d)};
const hours=(n:number)=>(n/60).toFixed(1)+' س';
const dayKey=(date:string)=>{const d=new Date(`${date}T12:00:00`);return ['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][d.getDay()]};
const timeValue=(v:string|null)=>v?new Date(v).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Africa/Cairo'}):'';
export default function EmployeeRanking(){
 const[from,setFrom]=useState(monthAgo()),[to,setTo]=useState(today()),[employees,setEmployees]=useState<any[]>([]),[attendance,setAttendance]=useState<any[]>([]),[branches,setBranches]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<any|null>(null);
 async function load(){setLoading(true);setError('');const[e,a,b]=await Promise.all([supabase.from('hr_v2_employees').select('*').eq('status','active').order('full_name_ar'),supabase.from('hr_v2_attendance').select('*').gte('work_date',from).lte('work_date',to),supabase.from('hr_v2_branches').select('id,name')]);if(e.error||a.error||b.error)setError(e.error?.message||a.error?.message||b.error?.message||'تعذر تحميل التحليل');else{setEmployees(e.data||[]);setAttendance(a.data||[]);setBranches(b.data||[])}setLoading(false)}
 useEffect(()=>{load()},[from,to]);
 const rows=useMemo(()=>{const bm=new Map(branches.map(b=>[b.id,b.name]));return employees.map(e=>{const rs=attendance.filter(a=>a.employee_id===e.id);let worked=0,late=0,ot=0,approvedOt=0,missing=0,pending=0,present=0;rs.forEach(r=>{worked+=Math.max(0,Number(r.work_minutes||0));if(r.check_in)present++;if(r.check_in&&!r.check_out)missing++;ot+=Math.max(0,Number(r.overtime_minutes||0));approvedOt+=Math.min(Math.max(0,Number(r.approved_overtime_minutes||0)),Math.max(0,Number(r.overtime_minutes||0)));if(r.schedule_exception_required&&!r.schedule_exception_approved)pending++;const sch=e.work_schedule?.[dayKey(r.work_date)];if(r.check_in&&sch?.enabled!==false&&sch?.start){const t=timeValue(r.check_in).split(':').map(Number),s=sch.start.split(':').map(Number);late+=Math.max(0,t[0]*60+t[1]-s[0]*60-s[1])}});const lateRate=present?Math.min(100,late/(present*60)*100):0;const missingRate=rs.length?missing/rs.length*100:0;const approval=ot?approvedOt/ot*100:100;const score=Math.round(Math.max(0,100-lateRate*.45-missingRate*.3-(100-approval)*.25));return{...e,branchName:bm.get(e.branch_id)||'بدون فرع',worked,late,ot,approvedOt,missing,pending,present,score,label:score>=90?'ممتاز':score>=75?'جيد':score>=60?'يحتاج متابعة':'يحتاج تدخل'}}).sort((a,b)=>b.score-a.score)},[employees,attendance,branches]);
 const filtered=rows.filter(r=>String(r.full_name_ar||'').includes(q)||String(r.position||'').includes(q)||String(r.branchName||'').includes(q));const best=rows[0],worst=rows.length?rows[rows.length-1]:null,avg=rows.length?Math.round(rows.reduce((n,r)=>n+r.score,0)/rows.length):0,need=rows.filter(r=>r.score<75).length;
 const detail=selected?attendance.filter(a=>a.employee_id===selected.id).sort((a,b)=>String(b.work_date).localeCompare(String(a.work_date))).slice(0,10):[];
 const open=(r:any)=>setSelected(r);
 return <div dir="rtl"><div className="page-head"><div><h2>ترتيب وتحليل الموظفين</h2><p>قراءة جماعية لأداء كل موظف خلال الفترة المختارة لمساعدة المالك في القرار.</p></div><button className="secondary" onClick={load} disabled={loading}><RefreshCw size={17}/> {loading?'جاري التحميل':'تحديث'}</button></div>
 <div className="panel" style={{marginBottom:16}}><div style={{display:'flex',gap:12,alignItems:'end',flexWrap:'wrap'}}><label>من<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>إلى<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><div className="search" style={{flex:1,minWidth:220}}><Search size={18}/><input placeholder="بحث بالاسم أو الوظيفة أو الفرع" value={q} onChange={e=>setQ(e.target.value)}/></div></div></div>
 {error&&<div className="error" style={{marginBottom:16}}>{error}</div>}
 <div className="stats-grid"><div className="stat-card"><UserRoundSearch size={20}/><span>موظفون نشطون</span><strong>{rows.length}</strong></div><div className="stat-card"><ArrowUp size={20}/><span>متوسط التقييم</span><strong>{avg}%</strong></div><div className="stat-card"><AlertTriangle size={20}/><span>يحتاجون متابعة</span><strong>{need}</strong></div><div className="stat-card"><span>🏆 أفضل موظف</span><strong>{best?.full_name_ar||'—'}</strong><small>{best?`${best.score}% — ${best.label}`:''}</small></div></div>
 <div className="report-grid" style={{marginBottom:16}}>{best&&<div className="report-card"><h3>🥇 الأفضل</h3><strong style={{fontSize:23}}>{best.full_name_ar}</strong><p>{best.position||'—'} • {best.branchName}</p><strong>{best.score}%</strong><button className="primary" style={{width:'100%',marginTop:10}} onClick={()=>open(best)}>فتح التحليل</button></div>}{worst&&<div className="report-card"><h3>🚨 الأكثر احتياجًا للمتابعة</h3><strong style={{fontSize:23}}>{worst.full_name_ar}</strong><p>{worst.position||'—'} • {worst.branchName}</p><strong>{worst.score}%</strong><button className="secondary" style={{width:'100%',marginTop:10}} onClick={()=>open(worst)}>فتح التحليل</button></div>}</div>
 <div className="panel table-wrap"><table><thead><tr><th>#</th><th>الموظف</th><th>الفرع</th><th>الوظيفة</th><th>التقييم</th><th>الحضور</th><th>التأخير</th><th>بدون انصراف</th><th>الإضافي</th><th>اعتماد الإضافي</th><th>خارج الموعد</th><th>الإجراء</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r.id}><td>{i+1}</td><td><b>{r.full_name_ar}</b></td><td>{r.branchName}</td><td>{r.position||'—'}</td><td><b>{r.score}%</b><br/><small>{r.label}</small></td><td>{r.present}</td><td>{hours(r.late)}</td><td>{r.missing}</td><td>{hours(r.ot)}</td><td>{r.ot?Math.round(r.approvedOt/r.ot*100):100}%</td><td>{r.pending}</td><td><button className="secondary" onClick={()=>open(r)}>التفاصيل</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">لا توجد بيانات مطابقة.</div>}</div>
 {selected&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.45)',zIndex:1000,display:'flex',alignItems:'center',justifyContent:'center',padding:16}} onClick={()=>setSelected(null)}><div className="panel" style={{width:'min(900px,100%)',maxHeight:'90vh',overflow:'auto'}} onClick={e=>e.stopPropagation()}><div className="page-head" style={{marginBottom:10}}><div><h2>{selected.full_name_ar}</h2><p>{selected.position||'—'} • {selected.branchName} • الفترة {from} إلى {to}</p></div><button className="secondary" onClick={()=>setSelected(null)}><X size={18}/> إغلاق</button></div><div className="stats-grid"><div className="stat-card"><span>التقييم</span><strong>{selected.score}%</strong><small>{selected.label}</small></div><div className="stat-card"><span>ساعات العمل</span><strong>{hours(selected.worked)}</strong></div><div className="stat-card"><span>التأخير</span><strong>{hours(selected.late)}</strong></div><div className="stat-card"><span>الإضافي المعتمد</span><strong>{hours(selected.approvedOt)}</strong></div></div><div className="report-card" style={{marginTop:14}}><h3>قرار المتابعة</h3><p>{selected.score<60?'يحتاج تدخل إداري واضح ومراجعة أسباب الأداء.':selected.score<75?'يحتاج متابعة مع المدير ومراجعة أسباب التأخير أو الغياب والانصراف.':selected.pending>0?'الأداء جيد لكن توجد طلبات حضور خارج المواعيد تحتاج اعتمادًا.':selected.ot>selected.approvedOt?'يوجد إضافي غير معتمد يحتاج مراجعة.':'الأداء مستقر ولا توجد إشارة حرجة في الفترة الحالية.'}</p></div><div className="panel table-wrap" style={{marginTop:14}}><h3>آخر سجلات الحضور</h3><table><thead><tr><th>التاريخ</th><th>الحضور</th><th>الانصراف</th><th>العمل</th><th>الإضافي</th><th>خارج الموعد</th></tr></thead><tbody>{detail.map(r=><tr key={r.id}><td>{r.work_date}</td><td>{timeValue(r.check_in)||'—'}</td><td>{timeValue(r.check_out)||'—'}</td><td>{hours(Number(r.work_minutes||0))}</td><td>{hours(Number(r.overtime_minutes||0))} {Number(r.overtime_minutes||0)>Number(r.approved_overtime_minutes||0)&&'⚠️'}</td><td>{r.schedule_exception_required?(r.schedule_exception_approved?'معتمد':'بانتظار الاعتماد'):'—'}</td></tr>)}</tbody></table>{!detail.length&&<div className="empty">لا توجد سجلات حضور في الفترة.</div>}</div><button className="primary" style={{width:'100%',marginTop:14}} onClick={()=>window.location.href=`/employee-review?employee=${selected.id}`}>فتح شاشة مراجعة الموظف</button></div></div>}
 </div>
}