/* Money transactions: advances, deductions, and bonuses are active immediately; owner/admin can edit or delete. */
import {useEffect,useState} from 'react';import {Edit3,Trash2,Plus} from 'lucide-react';import {supabase} from '../lib/supabase';import type {Profile} from '../types';
function numAr(n:any){return Number(n||0).toLocaleString('ar-EG',{maximumFractionDigits:2})}
export default function Money({profile}:{profile:Profile}){const role=String(profile.role||'').trim().toLowerCase(),isEmployee=role==='employee',canManageMoney=role==='owner'||role==='admin';const[r,setR]=useState<any[]>([]),[e,setE]=useState<any[]>([]),[show,setShow]=useState(false),[editing,setEditing]=useState<any>(null),[f,setF]=useState({employee_id:profile.employee_id||'',transaction_date:new Date().toISOString().slice(0,10),type:'advance',amount:'',reason:'',notes:''}),[err,setErr]=useState('');
async function load(){let q=supabase!.from('hr_v2_money_transactions').select('*').order('transaction_date',{ascending:false});if(isEmployee&&profile.employee_id)q=q.eq('employee_id',profile.employee_id);const{data,error}=await q;if(error)setErr(error.message);setR(data||[]);let xq=supabase!.from('hr_v2_employees').select('id,full_name_ar').eq('status','active').order('full_name_ar');if(isEmployee&&profile.employee_id)xq=xq.eq('id',profile.employee_id);const{data:x}=await xq;setE(x||[])}
useEffect(()=>{load()},[profile.employee_id,profile.role]);
function resetForm(){setF({employee_id:profile.employee_id||'',transaction_date:new Date().toISOString().slice(0,10),type:'advance',amount:'',reason:'',notes:''});setEditing(null);setShow(false)}
function startEdit(v:any){if(!canManageMoney)return;setEditing(v);setF({employee_id:v.employee_id,transaction_date:v.transaction_date,type:v.type,amount:String(v.amount??''),reason:v.reason||'',notes:v.notes||''});setErr('');setShow(true)}
async function add(){if(!f.employee_id||Number(f.amount)<=0){setErr('اختر الموظف وأدخل مبلغ صحيح');return}if(isEmployee&&(f.employee_id!==profile.employee_id||f.type!=='advance')){setErr('غير مسموح');return}
if(editing){if(!canManageMoney)return;const{error}=await supabase!.from('hr_v2_money_transactions').update({employee_id:f.employee_id,transaction_date:f.transaction_date,type:f.type,amount:Number(f.amount),reason:f.reason||null,notes:f.notes||null,approval_status:'approved',approved_by:null}).eq('id',editing.id);if(error)setErr(error.message);else{resetForm();setErr('');await load()}return}
const{error}=await supabase!.from('hr_v2_money_transactions').insert({...f,amount:Number(f.amount),approval_status:'approved',approved_by:null,reason:f.reason||null,notes:f.notes||null});if(error)setErr(error.message);else{resetForm();setErr('');await load()}}
async function remove(id:string){if(!canManageMoney||!confirm('هل تريد حذف هذه الحركة المالية نهائيًا؟'))return;setErr('');const{error}=await supabase!.from('hr_v2_money_transactions').delete().eq('id',id);if(error)setErr(error.message);else{setR(prev=>prev.filter(v=>v.id!==id));setErr('')}}
return <><div className="page-head"><div><h2>السلف والخصومات والمكافآت</h2><p>{isEmployee?'طلب السلفة وتظهر مباشرة في الحساب.':'إضافة وتعديل وحذف الحركات المالية — السلفة والخصم والمكافأة تتفعل فورًا بدون موافقة.'}</p></div><button className="primary" onClick={()=>{setEditing(null);setErr('');setF({employee_id:profile.employee_id||'',transaction_date:new Date().toISOString().slice(0,10),type:'advance',amount:'',reason:'',notes:''});setShow(true)}}><Plus size={18}/>{isEmployee?'طلب سلفة':'إضافة حركة'}</button></div><div className="panel table-wrap"><table><thead><tr><th>الموظف</th><th>التاريخ</th><th>النوع</th><th>المبلغ</th><th>السبب</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{r.map(v=><tr key={v.id}><td>{e.find(x=>x.id===v.employee_id)?.full_name_ar||v.employee_id}</td><td>{v.transaction_date}</td><td>{v.type==='advance'?'سلفة':v.type==='deduction'?'خصم':v.type==='bonus'?'مكافأة':'أخرى'}</td><td>{numAr(v.amount)} ج.م</td><td>{v.reason||'—'}</td><td>{v.approval_status==='rejected'?'مرفوضة':'مفعّلة'}</td><td style={{whiteSpace:'nowrap'}}>{canManageMoney&&<><button className="secondary" title="تعديل الحركة" onClick={()=>startEdit(v)}><Edit3 size={15}/> تعديل</button><button className="secondary" title="حذف الحركة" onClick={()=>remove(v.id)}><Trash2 size={15}/> حذف</button></>}</td></tr>)}</tbody></table>{!r.length&&<div className="empty">لا توجد حركات مالية.</div>}</div>{show&&<div className="modal-backdrop"><div className="modal"><h3>{editing?'تعديل الحركة المالية':isEmployee?'طلب سلفة':'إضافة حركة مالية'}</h3>{!isEmployee&&<label>الموظف<select value={f.employee_id} onChange={z=>setF({...f,employee_id:z.target.value})}><option value="">اختر الموظف</option>{e.map(x=><option key={x.id} value={x.id}>{x.full_name_ar}</option>)}</select></label>}<label>التاريخ<input type="date" value={f.transaction_date} onChange={z=>setF({...f,transaction_date:z.target.value})}/></label>{!isEmployee&&<label>النوع<select value={f.type} onChange={z=>setF({...f,type:z.target.value})}><option value="advance">سلفة</option><option value="deduction">خصم</option><option value="bonus">مكافأة</option><option value="other">أخرى</option></select></label>}<label>المبلغ<input type="number" min="0" value={f.amount} onChange={z=>setF({...f,amount:z.target.value})}/></label><label>السبب<input value={f.reason} onChange={z=>setF({...f,reason:z.target.value})}/></label><label>ملاحظات<input value={f.notes} onChange={z=>setF({...f,notes:z.target.value})}/></label>{err&&<div className="error">{err}</div>}<div className="modal-actions"><button className="secondary" onClick={resetForm}>إلغاء</button><button className="primary" onClick={add}>{editing?'حفظ التعديل':'حفظ'}</button></div></div></div>}</>}
