import {useEffect,useState} from 'react';
import {AlertTriangle,CheckCircle2,Clock3,RefreshCw,ChevronLeft,ShieldAlert} from 'lucide-react';
import {supabase} from '../lib/supabase';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());
const money=(v:any)=>Number(v||0).toLocaleString('ar-EG',{maximumFractionDigits:2})+' ج.م';
const time=(v:any)=>v?new Date(v).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit',timeZone:'Africa/Cairo'}):'—';
type Item={id:string;title:string;detail:string;count:number;level:'high'|'medium';path:string;records:any[]};
export default function Notifications(){
 const[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);const d=today();const[{data:att},{data:ot},{data:moneyRows},{data:close},{data:cust},{data:open}]=await Promise.all([
  supabase.from('hr_v2_attendance').select('id,employee_id,work_date,check_in,check_out,schedule_exception_required,schedule_exception_approved').eq('schedule_exception_required',true).eq('schedule_exception_approved',false).order('work_date',{ascending:false}),
  supabase.from('hr_v2_overtime').select('id,employee_id,work_date,hours,amount,reason').eq('approval_status','pending').order('work_date',{ascending:false}),
  supabase.from('hr_v2_money_transactions').select('id,employee_id,transaction_date,type,amount,reason').eq('approval_status','pending').order('transaction_date',{ascending:false}),
  supabase.from('hr_v2_shift_closeouts').select('id,branch_id,work_date,shift_label,cashier_employee_id,expected_cash,actual_cash,paper_image_path,paper_image_path_2').order('work_date',{ascending:false}).limit(300),
  supabase.from('hr_v2_shift_custody').select('id,closeout_id,custody_image_path,custody_image_path_2').limit(300),
  supabase.from('hr_v2_attendance').select('id,employee_id,work_date,check_in').eq('work_date',d).not('check_in','is',null).is('check_out',null)
 ]);if(!alive)return;
 const ids=[...(att||[]).map(x=>x.employee_id),...(ot||[]).map(x=>x.employee_id),...(moneyRows||[]).map(x=>x.employee_id),...(open||[]).map(x=>x.employee_id)];
 const eids=[...new Set(ids.filter(Boolean))];const{data:emps}=eids.length?await supabase.from('hr_v2_employees').select('id,full_name_ar,branch_id,position').in('id',eids):{data:[]};
 const{data:branches}=await supabase.from('hr_v2_branches').select('id,name');const em=new Map((emps||[]).map(x=>[x.id,x])),bm=new Map((branches||[]).map(x=>[x.id,x.name]));
 const list:Item[]=[];const names=(rows:any[])=>rows.slice(0,8).map(x=>em.get(x.employee_id)?.full_name_ar||'موظف');
 if(att?.length)list.push({id:'attendance',title:'حضور خارج المواعيد يحتاج اعتماد',detail:`${att.length} سجلًا يحتاج موافقة قبل احتساب الساعات. ${names(att).join('، ')}`,count:att.length,level:'high',path:'/attendance',records:att});
 if(ot?.length)list.push({id:'overtime',title:'إضافي يحتاج اعتماد',detail:`${ot.length} طلبًا معلّقًا. ${names(ot).join('، ')}`,count:ot.length,level:'medium',path:'/overtime',records:ot});
 if(moneyRows?.length)list.push({id:'money',title:'حركات مالية تحتاج اعتماد',detail:`${moneyRows.length} حركة معلّقة. ${names(moneyRows).join('، ')}`,count:moneyRows.length,level:'medium',path:'/money',records:moneyRows});
 const deficits=(close||[]).filter(x=>Number(x.actual_cash||0)-Number(x.expected_cash||0)<-0.01);if(deficits.length)list.push({id:'deficit',title:'تقفيلات بها عجز',detail:`${deficits.length} تقفيلة بها عجز وتحتاج مراجعة المالك.`,count:deficits.length,level:'high',path:'/closeouts',records:deficits});
 const missingPaper=(close||[]).filter(x=>!x.paper_image_path&&!x.paper_image_path_2);if(missingPaper.length)list.push({id:'paper',title:'تقفيلات بدون صورة ورقة',detail:`${missingPaper.length} تقفيلة تحتاج رفع المستند.`,count:missingPaper.length,level:'medium',path:'/closeouts',records:missingPaper});
 const cm=new Map((cust||[]).map(x=>[x.closeout_id,x]));const missingCustody=(close||[]).filter(x=>!cm.has(x.id));if(missingCustody.length)list.push({id:'custody',title:'تقفيلات بدون سجل عهدة',detail:`${missingCustody.length} تقفيلة تحتاج إنشاء العهدة.`,count:missingCustody.length,level:'medium',path:'/closeouts',records:missingCustody});
 const missingPhoto=(close||[]).filter(x=>{const c=cm.get(x.id);return c&&!c.custody_image_path&&!c.custody_image_path_2});if(missingPhoto.length)list.push({id:'custody-photo',title:'عهد بدون صورة',detail:`${missingPhoto.length} عهدة تحتاج صورة مستند.`,count:missingPhoto.length,level:'medium',path:'/closeouts',records:missingPhoto});
 if(open?.length)list.push({id:'checkout',title:'موظفون بدون انصراف اليوم',detail:`${open.length} حضور مفتوح حتى الآن. ${names(open).join('، ')}`,count:open.length,level:'high',path:'/attendance',records:open});
 const employeeIssue=new Map<string,number>();[...(att||[]),...(ot||[]),...(open||[])].forEach(r=>{if(r.employee_id)employeeIssue.set(r.employee_id,(employeeIssue.get(r.employee_id)||0)+1)});
 const criticalEmployees=(emps||[]).filter(e=>(employeeIssue.get(e.id)||0)>=3).sort((a,b)=>(employeeIssue.get(b.id)||0)-(employeeIssue.get(a.id)||0));
 if(criticalEmployees.length)list.push({id:'critical-employees',title:'تنبيه حرج: موظفون لديهم تكرار مشاكل',detail:`${criticalEmployees.length} موظفًا لديهم 3 حالات أو أكثر من الحضور خارج الموعد أو الإضافي المعلّق أو الحضور بدون انصراف.`,count:criticalEmployees.length,level:'high',path:'/employee-ranking',records:criticalEmployees.map(e=>({...e,issueCount:employeeIssue.get(e.id)||0}))});
 setItems(list);setLoading(false)})();return()=>{alive=false}},[refresh]);
 const total=items.reduce((n,x)=>n+x.count,0),urgent=items.filter(x=>x.level==='high').reduce((n,x)=>n+x.count,0),critical=items.filter(x=>x.id==='critical-employees').reduce((n,x)=>n+x.count,0);
 return <div dir="rtl"><div className="page-head" style={{alignItems:'center'}}><div><h2>🔔 مركز التنبيهات والمتابعة</h2><p>مركز قرار للمالك: الحالات الحرجة أولًا، ثم الحالات التي تحتاج متابعة.</p></div><button className="secondary" onClick={()=>setRefresh(x=>x+1)} disabled={loading}><RefreshCw size={17}/>{loading?'جاري التحديث':'تحديث'}</button></div>
 <div className="stats-grid"><div className="stat-card"><AlertTriangle size={20}/><span>إجمالي الحالات</span><strong>{total}</strong></div><div className="stat-card"><ShieldAlert size={20}/><span>عاجل للمالك</span><strong>{urgent}</strong></div><div className="stat-card"><CheckCircle2 size={20}/><span>للمتابعة</span><strong>{total-urgent}</strong></div><div className="stat-card"><span>🚨 موظفون حرجون</span><strong>{critical}</strong><small>تكرار 3 حالات أو أكثر</small></div></div>
 <div className="panel" style={{marginTop:18}}>{items.length===0?<div style={{padding:45,textAlign:'center'}}><CheckCircle2 size={44}/><h3>الوضع ممتاز</h3><p>لا توجد حالات تحتاج تدخل حاليًا.</p></div>:<div style={{display:'grid',gap:12}}>{items.sort((a,b)=>(a.level==='high'?0:1)-(b.level==='high'?0:1)).map(x=><div key={x.id} className="report-card" style={{borderRight:x.level==='high'?'4px solid #c62828':'4px solid #d89b00'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div style={{flex:1,minWidth:240}}><h3 style={{margin:'0 0 6px'}}>{x.level==='high'?'🚨':'⚠️'} {x.title} <span className="muted">({x.count})</span></h3><p style={{margin:0}}>{x.detail}</p></div><button className="primary" onClick={()=>window.location.href=x.path}>فتح الإجراء <ChevronLeft size={16}/></button></div><div style={{display:'grid',gap:5,marginTop:10}}>{x.records.slice(0,5).map((r:any,i:number)=><div key={r.id||i} style={{background:'#f7f7f7',padding:'7px 9px',borderRadius:7,fontSize:13}}>{x.id==='deficit'?`${bm.get(r.branch_id)||'فرع'} • ${r.work_date} • عجز ${money(Number(r.actual_cash||0)-Number(r.expected_cash||0))}`:x.id==='overtime'?`${em.get(r.employee_id)?.full_name_ar||'موظف'} • ${r.work_date} • ${Number(r.hours||0).toFixed(2)} ساعة • ${money(r.amount)}`:x.id==='money'?`${em.get(r.employee_id)?.full_name_ar||'موظف'} • ${r.transaction_date} • ${money(r.amount)} • ${r.reason||'بدون بيان'}`:x.id==='checkout'?`${em.get(r.employee_id)?.full_name_ar||'موظف'} • ${r.work_date} • حضور ${time(r.check_in)} بدون انصراف`:x.id==='attendance'?`${em.get(r.employee_id)?.full_name_ar||'موظف'} • ${r.work_date} • حضور ${time(r.check_in)} خارج الموعد`:x.id==='critical-employees'?`${r.full_name_ar} • ${r.position||'—'} • ${bm.get(r.branch_id)||'بدون فرع'} • ${r.issueCount} حالات تحتاج تدخل`:`${bm.get(r.branch_id)||'فرع'} • ${r.work_date} • يحتاج مراجعة`}</div>)}</div>{x.count>5&&<small className="muted" style={{display:'block',marginTop:6}}>يوجد {x.count-5} حالة أخرى — افتح الإجراء لمراجعتها.</small>}</div>)}</div>}</div></div>}
