import {useEffect,useState} from 'react';
import {AlertTriangle,CheckCircle2,ChevronLeft,RefreshCw,ShieldAlert} from 'lucide-react';
import {supabase} from '../lib/supabase';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());
const monthBounds=()=>{const d=today(),[y,m]=d.split('-').map(Number);const start=`${y}-${String(m).padStart(2,'0')}-01`;const next=new Date(Date.UTC(y,m,1));const end=`${next.getUTCFullYear()}-${String(next.getUTCMonth()+1).padStart(2,'0')}-01`;return{start,end}};
const money=(v:any)=>Number(v||0).toLocaleString('ar-EG',{maximumFractionDigits:2})+' ج.م';
const time=(v:any)=>v?new Date(v).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit',timeZone:'Africa/Cairo'}):'—';
type Item={id:string;title:string;detail:string;count:number;level:'high'|'medium';path:string;records:any[]};
export default function Notifications(){
 const[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);const d=today();const{start,end}=monthBounds();const[attendanceRes,overtimeRes,moneyRes,closeoutsRes,custodyRes,openRes]=await Promise.all([
  supabase.from('hr_v2_attendance').select('id,employee_id,work_date,check_in,check_out,schedule_exception_required,schedule_exception_approved').gte('work_date',start).lt('work_date',end).eq('schedule_exception_required',true).not('check_in','is',null).order('work_date',{ascending:false}),
  supabase.from('hr_v2_overtime').select('id,employee_id,work_date,hours,amount,reason').gte('work_date',start).lt('work_date',end).eq('approval_status','pending').order('work_date',{ascending:false}),
  supabase.from('hr_v2_money_transactions').select('id,employee_id,transaction_date,type,amount,reason').gte('transaction_date',start).lt('transaction_date',end).eq('approval_status','pending').order('transaction_date',{ascending:false}),
  supabase.from('hr_v2_shift_closeouts').select('id,branch_id,work_date,shift_label,cashier_employee_id,expected_cash,actual_cash,paper_image_path,paper_image_path_2').gte('work_date',start).lt('work_date',end).order('work_date',{ascending:false}).limit(300),
  supabase.from('hr_v2_shift_custody').select('id,closeout_id,custody_image_path,custody_image_path_2').limit(300),
  supabase.from('hr_v2_attendance').select('id,employee_id,work_date,check_in').eq('work_date',d).not('check_in','is',null).is('check_out',null),
 ]);if(!alive)return;const attendance=(attendanceRes.data||[]).filter((x:any)=>x.schedule_exception_required===true&&x.schedule_exception_approved!==true&&x.check_in);const overtime=overtimeRes.data||[],moneyRows=moneyRes.data||[],closeouts=closeoutsRes.data||[],custody=custodyRes.data||[],open=openRes.data||[];
 const employeeIds=[...new Set([...attendance,...overtime,...moneyRows,...open].map((x:any)=>x.employee_id).filter(Boolean))];const cashierIds=closeouts.map((x:any)=>x.cashier_employee_id).filter(Boolean);const allEmployeeIds=[...new Set([...employeeIds,...cashierIds])];
 const employeesRes=allEmployeeIds.length?await supabase.from('hr_v2_employees').select('id,full_name_ar,branch_id,position,work_schedule,daily_work_hours').in('id',allEmployeeIds):{data:[]};const employees=employeesRes.data||[];const branchesRes=await supabase.from('hr_v2_branches').select('id,name');const branches=branchesRes.data||[];
 const employeeMap=new Map<string,any>(employees.map((x:any)=>[x.id,x])),branchMap=new Map<string,string>(branches.map((x:any)=>[x.id,x.name]));const list:Item[]=[];const names=(rows:any[])=>rows.slice(0,8).map((x:any)=>employeeMap.get(x.employee_id)?.full_name_ar||'موظف');
 const ctx=(rows:any[])=>rows.map((x:any)=>{const e=employeeMap.get(x.employee_id);return{...x,employee_name:e?.full_name_ar||'موظف',employee_position:e?.position||'',employee_branch_id:e?.branch_id||''}});
 const attendanceRecords=ctx(attendance),overtimeRecords=ctx(overtime),moneyRecords=ctx(moneyRows),openRecords=ctx(open);const closeoutRecords=closeouts.map((x:any)=>({...x,branch_name:branchMap.get(x.branch_id)||'فرع',cashier_name:employeeMap.get(x.cashier_employee_id)?.full_name_ar||'—'}));
 if(attendance.length)list.push({id:'attendance',title:'حضور خارج المواعيد يحتاج اعتماد',detail:`${attendance.length} سجلًا يحتاج موافقة قبل احتساب الساعات هذا الشهر. ${names(attendance).join('، ')}`,count:attendance.length,level:'high',path:'/attendance',records:attendanceRecords});
 if(overtime.length)list.push({id:'overtime',title:'إضافي يحتاج اعتماد',detail:`${overtime.length} طلبًا معلّقًا هذا الشهر. ${names(overtime).join('، ')}`,count:overtime.length,level:'medium',path:'/overtime',records:overtimeRecords});
 if(moneyRows.length)list.push({id:'money',title:'حركات مالية تحتاج اعتماد',detail:`${moneyRows.length} حركة معلّقة هذا الشهر. ${names(moneyRows).join('، ')}`,count:moneyRows.length,level:'medium',path:'/money',records:moneyRecords});
 const deficits=closeouts.filter((x:any)=>Number(x.actual_cash||0)-Number(x.expected_cash||0)<-0.01);if(deficits.length)list.push({id:'deficit',title:'تقفيلات بها عجز',detail:`${deficits.length} تقفيلة بها عجز وتحتاج مراجعة المالك هذا الشهر.`,count:deficits.length,level:'high',path:'/closeouts',records:closeoutRecords.filter((x:any)=>Number(x.actual_cash||0)-Number(x.expected_cash||0)<-0.01)});
 const missingPaper=closeouts.filter((x:any)=>!x.paper_image_path&&!x.paper_image_path_2);if(missingPaper.length)list.push({id:'paper',title:'تقفيلات بدون صورة ورقة',detail:`${missingPaper.length} تقفيلة هذا الشهر تحتاج رفع المستند.`,count:missingPaper.length,level:'medium',path:'/closeouts',records:closeoutRecords.filter((x:any)=>!x.paper_image_path&&!x.paper_image_path_2)});
 const custodyMap=new Map<string,any>(custody.map((x:any)=>[x.closeout_id,x]));const missingCustody=closeouts.filter((x:any)=>!custodyMap.has(x.id));if(missingCustody.length)list.push({id:'custody',title:'تقفيلات بدون سجل عهدة',detail:`${missingCustody.length} تقفيلة هذا الشهر تحتاج إنشاء العهدة.`,count:missingCustody.length,level:'medium',path:'/closeouts',records:closeoutRecords.filter((x:any)=>!custodyMap.has(x.id))});
 const missingCustodyPhoto=closeouts.filter((x:any)=>{const c=custodyMap.get(x.id);return c&&!c.custody_image_path&&!c.custody_image_path_2});if(missingCustodyPhoto.length)list.push({id:'custody-photo',title:'عهد بدون صورة',detail:`${missingCustodyPhoto.length} عهدة هذا الشهر تحتاج صورة مستند.`,count:missingCustodyPhoto.length,level:'medium',path:'/closeouts',records:closeoutRecords.filter((x:any)=>{const c=custodyMap.get(x.id);return c&&!c.custody_image_path&&!c.custody_image_path_2})});
 if(open.length)list.push({id:'checkout',title:'موظفون بدون انصراف اليوم',detail:`${open.length} حضور مفتوح حتى الآن. ${names(open).join('، ')}`,count:open.length,level:'high',path:'/attendance',records:openRecords});
 const employeeIssues=new Map<string,number>();[...attendance,...overtime,...open].forEach((row:any)=>{if(row.employee_id)employeeIssues.set(row.employee_id,(employeeIssues.get(row.employee_id)||0)+1)});
 const criticalEmployees=employees.filter((e:any)=>(employeeIssues.get(e.id)||0)>=3).sort((a:any,b:any)=>(employeeIssues.get(b.id)||0)-(employeeIssues.get(a.id)||0));
 if(criticalEmployees.length)list.push({id:'critical-employees',title:'تنبيه حرج: موظفون لديهم تكرار مشاكل',detail:`${criticalEmployees.length} موظفًا لديهم 3 حالات أو أكثر من الحضور خارج الموعد أو الإضافي المعلّق أو الحضور بدون انصراف ضمن الشهر الحالي.`,count:criticalEmployees.length,level:'high',path:'/employee-review',records:criticalEmployees.map((e:any)=>({...e,issueCount:employeeIssues.get(e.id)||0,branch_name:branchMap.get(e.branch_id)||'فرع'}))});
 setItems(list);setLoading(false)})();const timer=window.setInterval(()=>setRefresh(x=>x+1),5000);return()=>{alive=false;window.clearInterval(timer)}},[refresh]);
 const total=items.reduce((n,x)=>n+x.count,0),urgent=items.filter(x=>x.level==='high').reduce((n,x)=>n+x.count,0),critical=items.filter(x=>x.id==='critical-employees').reduce((n,x)=>n+x.count,0),sortedItems=[...items].sort((a,b)=>(a.level==='high'?0:1)-(b.level==='high'?0:1));
 const actionPath=(item:Item,record?:any)=>{const first=record||item.records[0];if(item.id==='critical-employees'&&first?.id)return `/employee-review?employee=${encodeURIComponent(first.id)}`;if((item.id==='attendance'||item.id==='checkout')&&first?.work_date)return `/attendance?date=${first.work_date}${first?.employee_id?`&employee=${encodeURIComponent(first.employee_id)}`:''}`;if(item.id==='overtime'&&first?.work_date)return `/overtime?date=${first.work_date}${first?.employee_id?`&employee=${encodeURIComponent(first.employee_id)}`:''}`;if(item.id==='money'&&first?.transaction_date)return `/money?date=${first.transaction_date}${first?.employee_id?`&employee=${encodeURIComponent(first.employee_id)}`:''}`;if(item.id==='deficit'&&first?.work_date)return `/closeouts?date=${first.work_date}`;return item.path};
 const renderRecord=(item:Item,r:any)=>{const employeeName=r.employee_name||r.full_name_ar||'موظف',branchName=r.branch_name||'فرع';if(item.id==='deficit')return `${branchName} • ${r.work_date} • عجز ${money(Number(r.actual_cash||0)-Number(r.expected_cash||0))}`;if(item.id==='overtime')return `${employeeName} • ${r.work_date} • ${Number(r.hours||0).toFixed(2)} ساعة • ${money(r.amount)}`;if(item.id==='money')return `${employeeName} • ${r.transaction_date} • ${money(r.amount)} • ${r.reason||'بدون بيان'}`;if(item.id==='checkout')return `${employeeName} • ${r.work_date} • حضور ${time(r.check_in)} بدون انصراف`;if(item.id==='attendance')return `${employeeName} • ${r.work_date} • حضور ${time(r.check_in)} خارج الموعد`;if(item.id==='critical-employees')return `${r.full_name_ar} • ${r.position||'—'} • ${branchName} • ${r.issueCount} حالات تحتاج تدخل`;return `${branchName} • ${r.work_date} • يحتاج مراجعة`};
 return <div dir='rtl'><div className='page-head' style={{alignItems:'center'}}><div><h2>🔔 مركز التنبيهات والمتابعة</h2><p>مركز قرار للمالك: الحالات التي تحتاج إجراء فقط.</p></div><button className='secondary' onClick={()=>setRefresh(x=>x+1)} disabled={loading}><RefreshCw size={17}/> {loading?'جاري التحديث':'تحديث'}</button></div><div className='stats-grid'><div className='stat-card'><AlertTriangle size={20}/><span>إجمالي الحالات</span><strong>{total}</strong></div><div className='stat-card'><ShieldAlert size={20}/><span>عاجل للمالك</span><strong>{urgent}</strong></div><div className='stat-card'><CheckCircle2 size={20}/><span>للمتابعة</span><strong>{total-urgent}</strong></div><div className='stat-card'><span>🚨 موظفون حرجون</span><strong>{critical}</strong><small>تكرار 3 حالات أو أكثر</small></div></div><div className='panel' style={{marginTop:18}}>{items.length===0?<div style={{padding:45,textAlign:'center'}}><CheckCircle2 size={44}/><h3>الوضع ممتاز</h3><p>لا توجد حالات تحتاج تدخل حاليًا.</p></div>:<div style={{display:'grid',gap:12}}>{sortedItems.map(item=><div key={item.id} className='report-card' style={{borderRight:item.level==='high'?'4px solid #c62828':'4px solid #d89b00'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div style={{flex:1,minWidth:240}}><h3 style={{margin:'0 0 6px'}}>{item.level==='high'?'🚨':'⚠️'} {item.title} <span className='muted'>({item.count})</span></h3><p style={{margin:0}}>{item.detail}</p></div><button className='primary' onClick={()=>{window.location.href=actionPath(item)}}>فتح أول إجراء <ChevronLeft size={16}/></button></div><div style={{display:'grid',gap:5,marginTop:10}}>{item.records.slice(0,5).map((record:any,index:number)=><div key={record.id||index} style={{background:'#f7f7f7',padding:'7px 9px',borderRadius:7,fontSize:13,display:'flex',justifyContent:'space-between',gap:8,alignItems:'center'}}><span>{renderRecord(item,record)}</span>{(record.work_date||record.transaction_date)&&<button className='secondary' style={{padding:'4px 8px',fontSize:12,whiteSpace:'nowrap'}} onClick={()=>{window.location.href=actionPath(item,record)}}>فتح</button>}</div>)}</div>{item.count>5&&<small className='muted' style={{display:'block',marginTop:6}}>يوجد {item.count-5} حالة أخرى — افتح أول إجراء أو اختر السجل المطلوب.</small>}</div>)}</div>}</div></div>;
}