import {useEffect,useState} from 'react';
import {Calculator,Check,Printer,Send} from 'lucide-react';
import {supabase} from '../lib/supabase';
import type {Profile} from '../types';
function money(n:any){return Number(n||0).toLocaleString('ar-EG',{maximumFractionDigits:2})+' ج.م'}
function deliveryWeek(){const d=new Date();const diff=(d.getDay()+1)%7;const sat=new Date(d);sat.setDate(d.getDate()-diff);const fri=new Date(sat);fri.setDate(sat.getDate()+6);return [sat.toISOString().slice(0,10),fri.toISOString().slice(0,10)]}
function safe(s:any){return String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'} as any)[m])}
function egyptWhatsapp(phone:any){let d=String(phone||'').replace(/\D/g,'');if(d.startsWith('00'))d=d.slice(2);if(d.startsWith('20'))return d;if(d.startsWith('0'))return '20'+d.slice(1);return d}
export default function Payroll({profile}:{profile:Profile}){
 const isEmployee=profile.role==='employee',isAccountant=profile.role==='accountant',canApprove=profile.role==='owner'||profile.role==='admin';
 const[r,setR]=useState<any[]>([]),[e,setE]=useState<any[]>([]),[delivery,setDelivery]=useState<any[]>([]),[start,setStart]=useState(new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10)),[end,setEnd]=useState(new Date(new Date().getFullYear(),new Date().getMonth()+1,0).toISOString().slice(0,10)),[week,setWeek]=useState(deliveryWeek()),[busy,setBusy]=useState('');
 async function load(){if(isAccountant){const{data,error}=await supabase!.rpc('hr_v2_get_delivery_payroll',{p_start:week[0],p_end:week[1]});if(!error)setDelivery(Array.isArray(data)?data:[]);return}let q=supabase!.from('hr_v2_payroll').select('*').order('period_end',{ascending:false});if(isEmployee&&profile.employee_id)q=q.eq('employee_id',profile.employee_id);const{data}=await q;setR(data||[]);let xq=supabase!.from('hr_v2_employees').select('id,full_name_ar,phone,is_delivery,payroll_cycle').order('full_name_ar');if(isEmployee&&profile.employee_id)xq=xq.eq('id',profile.employee_id);const{data:x}=await xq;setE(x||[])}
 useEffect(()=>{load()},[profile.employee_id,profile.role,week[0],week[1]]);
 async function generate(kind:'monthly'|'delivery'){if(isEmployee||(isAccountant&&kind!=='delivery'))return;setBusy(kind);const emps=e.filter(x=>kind==='delivery'?x.payroll_cycle==='weekly_delivery':x.payroll_cycle!=='weekly_delivery');const [s,t]=kind==='delivery'?week:[start,end];for(const x of emps){const{data:c}=await supabase!.rpc('hr_v2_calc_payroll',{p_employee:x.id,p_start:s,p_end:t});if(c)await supabase!.from('hr_v2_payroll').upsert({employee_id:x.id,period_start:s,period_end:t,...c,status:'draft'},{onConflict:'employee_id,period_start,period_end'})}await load();setBusy('')}
 async function status(id:string,s:'approved'|'paid'){if(!canApprove)return;const u=(await supabase!.auth.getUser()).data.user?.id;await supabase!.from('hr_v2_payroll').update({status:s,approved_by:u,approved_at:new Date().toISOString()}).eq('id',id);load()}
 function statement(v:any,send:boolean){const emp=e.find(x=>x.id===v.employee_id);const text=`ألبان فلاحي\nكشف حساب الداليفري: ${emp?.full_name_ar||v.full_name_ar||''}\nالفترة: ${v.period_start} إلى ${v.period_end}\n\nإجمالي الساعات: ${Number(v.total_hours||0).toFixed(2)}\nالساعات المدفوعة: ${Number(v.paid_hours??(v.paid_minutes||0)/60).toFixed(2)}\nالأساسي: ${money(v.base_amount)}\nالإضافي المعتمد: ${money(v.overtime_amount)}\nالمكافآت: ${money(v.bonuses)}\nالخصومات: ${money(v.deductions)}\nالسلف: ${money(v.advances)}\n\nصافي الحساب: ${money(v.net_amount)}\n\nنظام الموارد البشرية - ألبان فلاحي`;if(send&&(emp?.phone||v.phone)){const digits=egyptWhatsapp(emp?.phone||v.phone);if(digits)window.open(`https://wa.me/${digits}?text=${encodeURIComponent(text)}`,'_blank');return}const w=window.open('','_blank','width=700,height=800');if(w){w.document.write(`<html dir="rtl"><head><title>كشف ${safe(emp?.full_name_ar||v.full_name_ar)}</title><style>body{font-family:Tahoma,Arial;padding:40px;line-height:2}table{width:100%;border-collapse:collapse}td{border-bottom:1px solid #ddd;padding:8px}</style></head><body><h1>ألبان فلاحي</h1><h2>كشف حساب الداليفري</h2><p>${safe(emp?.full_name_ar||v.full_name_ar)} — ${v.period_start} إلى ${v.period_end}</p><table><tr><td>إجمالي الساعات</td><td>${Number(v.total_hours||0).toFixed(2)}</td></tr><tr><td>الساعات المدفوعة</td><td>${Number(v.paid_hours??(v.paid_minutes||0)/60).toFixed(2)}</td></tr><tr><td>الأساسي</td><td>${money(v.base_amount)}</td></tr><tr><td>الإضافي المعتمد</td><td>${money(v.overtime_amount)}</td></tr><tr><td>المكافآت</td><td>${money(v.bonuses)}</td></tr><tr><td>الخصومات</td><td>${money(v.deductions)}</td></tr><tr><td>السلف</td><td>${money(v.advances)}</td></tr><tr><td><b>صافي الحساب</b></td><td><b>${money(v.net_amount)}</b></td></tr></table><script>window.print()</script></body></html>`);w.document.close()}}
 if(isAccountant)return <><div className="page-head"><div><h2>حساب الداليفري الأسبوعي</h2><p>كل تفاصيل الحساب: الساعات، المستحق، السلف، الخصومات، المكافآت وصافي الحساب.</p></div><div className="panel" style={{padding:10}}><label>من السبت<input type="date" value={week[0]} onChange={x=>setWeek([x.target.value,week[1]])}/></label><label>إلى الجمعة<input type="date" value={week[1]} onChange={x=>setWeek([week[0],x.target.value])}/></label></div></div><div className="panel table-wrap"><table><thead><tr><th>الموظف</th><th>إجمالي الساعات</th><th>المدفوعة</th><th>الأساسي</th><th>إضافي معتمد</th><th>مكافآت</th><th>خصومات</th><th>سلف</th><th>صافي الحساب</th><th>كشف</th></tr></thead><tbody>{delivery.map(v=><tr key={v.employee_id}><td><b>{v.full_name_ar}</b><br/><small>{v.phone||''}</small></td><td>{Number(v.total_hours||0).toFixed(2)}</td><td>{Number(v.paid_hours??(v.paid_minutes||0)/60).toFixed(2)}</td><td>{money(v.base_amount)}</td><td>{money(v.overtime_amount)}</td><td>{money(v.bonuses)}</td><td>{money(v.deductions)}</td><td>{money(v.advances)}</td><td><b>{money(v.net_amount)}</b></td><td><button className="icon-btn" onClick={()=>statement(v,false)}><Printer size={17}/></button>{v.phone&&<button className="icon-btn" onClick={()=>statement(v,true)}><Send size={17}/></button>}</td></tr>)}</tbody></table>{!delivery.length&&<div className="empty">لا يوجد حسابات داليفري في هذا الأسبوع.</div>}</div></>;
 const rows=isEmployee?r:r.filter(v=>{const emp=e.find(x=>x.id===v.employee_id);return emp?.payroll_cycle==='weekly_delivery'||(v.period_start===start&&v.period_end===end)});
 return <><div className="page-head"><div><h2>الرواتب والمستحقات</h2><p>مسير شهري للموظفين + مسير أسبوعي للدليفري.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="primary" disabled={!!busy} onClick={()=>generate('monthly')}><Calculator size={18}/>حساب الرواتب الشهرية</button><button className="secondary" disabled={!!busy} onClick={()=>generate('delivery')}><Calculator size={18}/>حساب الدليفري الأسبوعي</button></div></div><div className="panel" style={{marginBottom:14}}><div className="form-grid"><label>فترة الموظفين من<input type="date" value={start} onChange={x=>setStart(x.target.value)}/></label><label>إلى<input type="date" value={end} onChange={x=>setEnd(x.target.value)}/></label><label>أسبوع الدليفري من السبت<input type="date" value={week[0]} onChange={x=>setWeek([x.target.value,week[1]])}/></label><label>إلى الجمعة<input type="date" value={week[1]} onChange={x=>setWeek([week[0],x.target.value])}/></label></div></div><div className="panel table-wrap"><table><thead><tr><th>الموظف</th><th>الفترة</th><th>الأساسي/الساعات</th><th>الإضافي</th><th>المكافآت</th><th>الخصومات</th><th>السلف</th><th>الصافي</th><th>الحالة</th><th>كشف</th></tr></thead><tbody>{rows.map(v=>{const totalDed=Number(v.deductions||0)+Number(v.attendance_deduction||0)+Number(v.lateness_deduction||0);const emp=e.find(x=>x.id===v.employee_id);return <tr key={v.id}><td>{emp?.full_name_ar||v.employee_id}</td><td>{v.period_start} → {v.period_end}</td><td>{money(v.base_salary)}</td><td>{money(v.overtime_total)}</td><td>{money(v.bonuses)}</td><td>{money(totalDed)}</td><td>{money(v.advances)}</td><td><b>{money(v.net_salary)}</b></td><td>{v.status==='draft'?'مسودة':v.status==='approved'?'معتمد':'تم الصرف'}</td><td><button className="icon-btn" onClick={()=>statement(v,false)}><Printer size={17}/></button>{emp?.phone&&<button className="icon-btn" onClick={()=>statement(v,true)}><Send size={17}/></button>}{canApprove&&v.status==='draft'&&<button className="icon-btn" onClick={()=>status(v.id,'approved')}><Check size={17}/></button>}{canApprove&&v.status==='approved'&&<button className="icon-btn" onClick={()=>status(v.id,'paid')}><Printer size={17}/></button>}</td></tr>})}</tbody></table>{!rows.length&&<div className="empty">لا توجد مسيرات محسوبة للفترة الحالية.</div>}</div></>;
}