import {useEffect,useState} from 'react';
import {Edit3,Plus,ShieldCheck,UsersRound} from 'lucide-react';
import {supabase} from '../lib/supabase';
const roles:any={owner:'المالك',admin:'مدير النظام',accountant:'محاسب',employee:'موظف',attendance_operator:'مسؤول حضور وانصراف'};
const blank={full_name:'',phone:'',role:'accountant',employee_id:'',branch_id:'',password:'',is_active:true};
export default function Users(){
 const[rows,setRows]=useState<any[]>([]),[employees,setEmployees]=useState<any[]>([]),[branches,setBranches]=useState<any[]>([]),[show,setShow]=useState(false),[edit,setEdit]=useState<any>(null),[form,setForm]=useState<any>(blank),[error,setError]=useState(''),[busy,setBusy]=useState(false),[bulkBusy,setBulkBusy]=useState(false),[bulkMsg,setBulkMsg]=useState('');
 async function load(){const[{data:a,error:ae},{data:e,error:ee}]=await Promise.all([supabase.from('hr_v2_accounts').select('id,full_name,phone,role,employee_id,branch_id,is_active,permissions').order('full_name'),supabase.from('hr_v2_employees').select('id,full_name_ar,phone').eq('status','active').order('full_name_ar')]);if(ae||ee){setError(ae?.message||ee?.message||'تعذر تحميل المستخدمين');return}const{data:b,error:be}=await supabase.from('hr_v2_branches').select('id,name').eq('is_active',true).order('name');if(be){setError(be.message);return}setRows(a||[]);setEmployees(e||[]);setBranches(b||[])}
 useEffect(()=>{load()},[]);
 function openAdd(){setEdit(null);setForm({...blank});setError('');setShow(true)}
 function openEdit(r:any){setEdit(r);setForm({full_name:r.full_name||'',phone:r.phone||'',role:r.role,employee_id:r.employee_id||'',branch_id:r.branch_id||'',password:'',is_active:!!r.is_active});setError('');setShow(true)}

 async function createMissingEmployees(){setEdit(null);setForm({...blank,role:'employee',employee_id:'',phone:'',password:''});setError('');setBulkMsg('');setShow(true)}
 async function save(){if(!form.full_name.trim()||!form.phone.trim())return setError('الاسم والموبايل مطلوبان');if(['employee','accountant'].includes(form.role)&&!form.employee_id)return setError('اختر الموظف المرتبط بالحساب');if(form.role==='attendance_operator'&&!form.branch_id)return setError('اختر الفرع لمسؤول الحضور والانصراف');if(!edit&&!form.password&&form.role!=='employee'&&form.role!=='attendance_operator')return setError('كلمة المرور مطلوبة');setBusy(true);setError('');const r=await supabase.functions.invoke('hr-v2-admin-user-v2',{body:{user_id:edit?.id,full_name:form.full_name,phone:form.phone,password:form.password||undefined,role:form.role,employee_id:['employee','accountant'].includes(form.role)?form.employee_id:null,branch_id:form.role==='attendance_operator'?form.branch_id:null,is_active:form.is_active,permissions:form.role==='accountant'?{attendance:true,closeouts:true,money:true,weekly_delivery_payroll:true}:{}}});if(r.error||r.data?.error)setError(r.error?.message||r.data?.error||'تعذر حفظ الحساب');else{setShow(false);setBulkMsg(edit?'تم تحديث الحساب بنجاح.': 'تم إنشاء حساب الموظف بنجاح. كلمة المرور الأولية: '+(form.password||'123456'));await load()}setBusy(false)}
 async function resetPassword(){if(!edit)return;const p=window.prompt('اكتب كلمة المرور الجديدة');if(!p)return;if(p.length<6)return setError('كلمة المرور يجب أن تكون 6 أحرف/أرقام على الأقل');setBusy(true);setError('');const r=await supabase.functions.invoke('hr-v2-admin-user-v2',{body:{user_id:edit.id,full_name:form.full_name,phone:form.phone,password:p,role:form.role,employee_id:['employee','accountant'].includes(form.role)?form.employee_id:null,branch_id:form.role==='attendance_operator'?form.branch_id:null,is_active:form.is_active,permissions:form.role==='accountant'?{attendance:true,closeouts:true,money:true,weekly_delivery_payroll:true}:{}}});if(r.error||r.data?.error)setError(r.error?.message||r.data?.error||'تعذر تغيير كلمة المرور');else{setBulkMsg('تم تغيير كلمة المرور وإجبار المستخدم على تغييرها عند الدخول القادم.');setShow(false);await load()}setBusy(false)}
 const missing=employees.filter(e=>!rows.some(r=>r.employee_id===e.id));
 return <><div className="page-head"><div><h2>المستخدمون والصلاحيات</h2><p>حسابات الإدارة والموظفين. حساب الموظف يستخدم رقم الموبايل وكلمة المرور الأولية 123456، ويُطلب منه تغييرها أول مرة.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="secondary" onClick={createMissingEmployees} disabled={bulkBusy}><UsersRound size={18}/>{bulkBusy?'جاري إنشاء الحسابات...':'إنشاء حسابات الموظفين'}</button><button className="primary" onClick={openAdd}><Plus size={18}/>إضافة مستخدم</button></div></div>
 <div className="panel" style={{marginBottom:14}}><div style={{display:'flex',gap:10,alignItems:'center'}}><ShieldCheck size={22}/><span>الموظف لا يرى لوحة الإدارة؛ بعد تسجيل الدخول يرى فقط كشوف الفترات التي تم اعتمادها نهائيًا.</span></div></div>{bulkMsg&&<div className="success" style={{marginBottom:12}}>{bulkMsg}</div>}
 <div className="panel table-wrap"><table><thead><tr><th>الاسم</th><th>الموبايل</th><th>الدور</th><th>الفرع</th><th>الموظف المرتبط</th><th>الحالة</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.full_name}</td><td>{r.phone||'—'}</td><td>{r.role==='accountant'&&r.employee_id?'محاسب + موظف':roles[r.role]||r.role}</td><td>{branches.find((b:any)=>b.id===r.branch_id)?.name||'—'}</td><td>{employees.find(e=>e.id===r.employee_id)?.full_name_ar||'—'}</td><td>{r.is_active?'نشط':'متوقف'}</td><td><button className="icon-btn" onClick={()=>openEdit(r)}><Edit3 size={17}/></button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">لا توجد حسابات بعد.</div>}</div>
 {show&&<div className="modal-backdrop"><div className="modal"><h3>{edit?'تعديل مستخدم':'إنشاء حساب موظف'}</h3><div className="form-grid"><label>الاسم *<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>الموبايل *<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>الدور<select value={form.role} onChange={e=>setForm({...form,role:e.target.value,employee_id:e.target.value==='employee'?form.employee_id:''})}><option value="accountant">محاسب</option><option value="employee">موظف</option><option value="attendance_operator">مسؤول حضور وانصراف</option></select></label>{['employee','accountant'].includes(form.role)&&<label>الموظف المرتبط<select value={form.employee_id} onChange={e=>{const id=e.target.value;const emp=employees.find((x:any)=>x.id===id);setForm({...form,employee_id:id,full_name:emp?.full_name_ar||form.full_name,phone:emp?.phone||form.phone})}}><option value="">اختر الموظف</option>{employees.filter((e:any)=>!rows.some((r:any)=>r.employee_id===e.id)||e.id===form.employee_id).map((e:any)=><option key={e.id} value={e.id}>{e.full_name_ar}</option>)}</select></label>}{form.role==='attendance_operator'&&<label>الفرع *<select value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})}><option value="">اختر الفرع</option>{branches.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}{form.role==='employee'&&!edit?<label>كلمة المرور الأولية (اختياري)<input type="password" placeholder="اتركها فارغة = 123456" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>:<label>{edit?'كلمة مرور جديدة (اختياري)':'كلمة المرور *'}<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>}<label>الحالة<select value={form.is_active?'active':'inactive'} onChange={e=>setForm({...form,is_active:e.target.value==='active'})}><option value="active">نشط</option><option value="inactive">متوقف</option></select></label></div>{error&&<div className="error">{error}</div>}<div className="modal-actions">{edit&&<button className="secondary" disabled={busy} onClick={resetPassword}>تغيير كلمة المرور</button>}<button className="secondary" onClick={()=>setShow(false)}>إلغاء</button><button className="primary" disabled={busy} onClick={save}>{busy?'جاري الحفظ...':edit?'حفظ التعديلات':'إنشاء الحساب'}</button></div></div></div>}</>;
}