import {useEffect,useState} from 'react';
import {Edit3,Plus,ShieldCheck} from 'lucide-react';
import {supabase} from '../lib/supabase';
const roles:any={admin:'مدير النظام',accountant:'محاسب',employee:'موظف'};
const blank={full_name:'',phone:'',role:'accountant',employee_id:'',password:'',is_active:true};
export default function Users(){
 const[rows,setRows]=useState<any[]>([]),[employees,setEmployees]=useState<any[]>([]),[show,setShow]=useState(false),[edit,setEdit]=useState<any>(null),[form,setForm]=useState<any>(blank),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){if(!supabase)return;const[{data:a},{data:e}]=await Promise.all([supabase.from('hr_v2_accounts').select('id,full_name,phone,role,employee_id,is_active,permissions').order('full_name'),supabase.from('hr_v2_employees').select('id,full_name_ar').eq('status','active').order('full_name_ar')]);setRows(a||[]);setEmployees(e||[])}
 useEffect(()=>{load()},[]);
 function openAdd(){setEdit(null);setForm({...blank});setError('');setShow(true)}
 function openEdit(r:any){setEdit(r);setForm({full_name:r.full_name||'',phone:r.phone||'',role:r.role,employee_id:r.employee_id||'',password:'',is_active:!!r.is_active});setError('');setShow(true)}
 async function save(){if(!supabase)return;if(!form.full_name.trim()||!form.phone.trim())return setError('الاسم والموبايل مطلوبان');if(!edit&&!form.password)return setError('كلمة المرور مطلوبة');if(form.role==='employee'&&!form.employee_id)return setError('اختر الموظف المرتبط بالحساب');setBusy(true);setError('');const r=await supabase.functions.invoke('hr-v2-admin-user',{body:{user_id:edit?.id,full_name:form.full_name,phone:form.phone,password:form.password||undefined,role:form.role,employee_id:form.role==='employee'?form.employee_id:null,is_active:form.is_active,permissions:form.role==='accountant'?{attendance:true,overtime:true,money:true,payroll:true,reports:true}: {}}});if(r.error||r.data?.error)setError(r.error?.message||r.data?.error||'تعذر حفظ الحساب');else{setShow(false);await load()}setBusy(false)}
 return <><div className="page-head"><div><h2>المستخدمون والصلاحيات</h2><p>إنشاء حسابات المحاسبين والموظفين والتحكم في تفعيلها ودورها.</p></div><button className="primary" onClick={openAdd}><Plus size={18}/>إضافة مستخدم</button></div><div className="panel" style={{marginBottom:14}}><div style={{display:'flex',gap:10,alignItems:'center'}}><ShieldCheck size={22}/><span>مدير النظام هو صاحب أعلى صلاحية. المحاسب له شاشة الحضور والعمليات المالية والرواتب والتقارير، والموظف له حسابه الذاتي فقط.</span></div></div><div className="panel table-wrap"><table><thead><tr><th>الاسم</th><th>الموبايل</th><th>الدور</th><th>الموظف المرتبط</th><th>الحالة</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.full_name}</td><td>{r.phone||'—'}</td><td>{roles[r.role]||r.role}</td><td>{employees.find(e=>e.id===r.employee_id)?.full_name_ar||'—'}</td><td>{r.is_active?'نشط':'متوقف'}</td><td><button className="icon-btn" onClick={()=>openEdit(r)}><Edit3 size={17}/></button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">لا توجد حسابات بعد.</div>}</div>{show&&<div className="modal-backdrop"><div className="modal"><h3>{edit?'تعديل مستخدم':'إضافة مستخدم'}</h3><div className="form-grid"><label>الاسم *<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>الموبايل *<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>الدور<select value={form.role} onChange={e=>setForm({...form,role:e.target.value,employee_id:e.target.value==='employee'?form.employee_id:''})}><option value="accountant">محاسب</option><option value="employee">موظف</option>{!edit&&<option value="admin">مدير النظام</option>}</select></label>{form.role==='employee'&&<label>الموظف<select value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})}><option value="">اختر الموظف</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name_ar}</option>)}</select></label>}<label>{edit?'كلمة مرور جديدة (اختياري)':'كلمة المرور *'}<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>الحالة<select value={form.is_active?'active':'inactive'} onChange={e=>setForm({...form,is_active:e.target.value==='active'})}><option value="active">نشط</option><option value="inactive">متوقف</option></select></label></div>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button className="secondary" onClick={()=>setShow(false)}>إلغاء</button><button className="primary" disabled={busy} onClick={save}>{busy?'جاري الحفظ...':'حفظ المستخدم'}</button></div></div></div>}</>;
}
