import { db, router, json, error, auth } from '@appdeploy/sdk';

type Role = 'owner' | 'accounts';
type Table = 'employees' | 'branches' | 'attendance' | 'overtime' | 'money' | 'audit';
type Account = { id?: string; userId?: string; email?: string; name: string; role: Role; username?: string; passwordHash?: string; permissions?: any };
const TABLES: Table[] = ['employees','branches','attendance','overtime','money','audit'];
const SECTIONS = ['الرئيسية','الموظفين','الفروع','الحضور والانصراف','المرتبات','السُلف والخصومات','المكافآت والتسويات','التقارير','حسابات الداش بورد','الإعدادات'];
const DEFAULT_PERMISSIONS = { view: Object.fromEntries(SECTIONS.map(x => [x, x !== 'حسابات الداش بورد' && x !== 'الإعدادات'])), actions: { add: true, edit: true, delete: false, approve: true, manageAccounts: false } };
async function accounts(){ return (await db.list<Account>('dashboard_accounts',{limit:100})).items; }
async function hashPassword(password:string){ const bytes=new TextEncoder().encode(password); const digest=await crypto.subtle.digest('SHA-256',bytes); return Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join(''); }
function cookie(event:any,name:string){ const raw=event?.headers?.cookie||event?.headers?.Cookie||''; const part=raw.split(';').map((x:string)=>x.trim()).find((x:string)=>x.startsWith(`${name}=`)); return part?decodeURIComponent(part.slice(name.length+1)):''; }
function cookieHeader(token:string,maxAge=2592000){ return `af_session=${encodeURIComponent(token)}; Path=/; Max-Age=${maxAge}; SameSite=Lax; HttpOnly`; }
async function session(event:any){ const token=cookie(event,'af_session'); if(!token)return null; const rows=(await db.list<any>('dashboard_sessions',{limit:100})).items; const s=rows.find((x:any)=>x.token===token&&new Date(x.expiresAt).getTime()>Date.now()); if(!s)return null; const all=await accounts(); return all.find(x=>x.id===s.accountId)||null; }
async function current(ctx:any):Promise<Account|null>{ const s=await session(ctx.event); if(s)return s; const u=await auth.getUser(ctx.event); if(!u)return null; const all=await accounts(); let m=all.find(x=>x.userId===u.userId); if(!m&&all.length===0){ const [id]=await db.add('dashboard_accounts',[{userId:u.userId,email:u.email||'',name:u.name||'علي إبراهيم',role:'owner',permissions:{view:Object.fromEntries(SECTIONS.map(x=>[x,true])),actions:{add:true,edit:true,delete:true,approve:true,manageAccounts:true}}}]); if(!id)return null; m={id,userId:u.userId,email:u.email||'',name:u.name||'علي إبراهيم',role:'owner'} as Account; } return m||null; }
function isOwner(m:Account|null){return m?.role==='owner';}
function canView(m:Account,s:string){return m.role==='owner'||m.role==='accounts'||m.permissions?.view?.[s]===true;}
function canAction(m:Account,a:string){return m.role==='owner'||m.role==='accounts'||m.permissions?.actions?.[a]===true;}
function sectionFor(table:Table){return table==='employees'?'الموظفين':table==='branches'?'الفروع':table==='attendance'||table==='overtime'?'الحضور والانصراف':table==='money'?'السُلف والخصومات':'الإعدادات';}
async function audit(m:Account,action:string,target:string){await db.add('audit',[{actor:m.name,action,target,date:new Date().toISOString()}]);}
async function list(table:Table){return (await db.list(table,{limit:200})).items;}
async function employeeAccounts(){return (await db.list<any>('employee_accounts',{limit:200})).items;}
function employeeCookieHeader(token:string,maxAge=2592000){return `ef_session=${encodeURIComponent(token)}; Path=/; Max-Age=${maxAge}; SameSite=Lax; HttpOnly`;}
function cairoNow(){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const get=(t:string)=>parts.find(x=>x.type===t)?.value||'';return {date:`${get('year')}-${get('month')}-${get('day')}`,time:`${get('hour')}:${get('minute')}`};}
function weekdayName(date:string){const d=new Date(`${date}T12:00:00Z`);return ['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'][d.getUTCDay()];}
function employeeSchedule(employee:any,date:string){const day=weekdayName(date);const s=employee.weekSchedule?.[day];if(s)return s;if(employee.start&&employee.end)return {start:employee.start,end:employee.end,off:false};return {start:'',end:'',off:false};}
function lateMinutesFor(employee:any,date:string,time:string){const s=employeeSchedule(employee,date);if(!s||s.off||!s.start)return 0;const [h,m]=String(s.start).split(':').map(Number);const [ah,am]=time.split(':').map(Number);return Math.max(0,(ah*60+am)-(h*60+m));}
async function employeeContext(ctx:any){const a=await employeeSession(ctx.event);if(!a)return null;const [employee]=await db.get<any>('employees',[a.employeeId]);if(!employee||employee.status==='موقوف')return null;return {account:a,employee};}
async function todayAttendance(employeeId:string,date:string){return (await db.list<any>('attendance',{limit:200})).items.find((x:any)=>x.employeeId===employeeId&&x.date===date)||null;}
async function employeeSession(event:any){const token=cookie(event,'ef_session');if(!token)return null;const rows=(await db.list<any>('employee_sessions',{limit:200})).items;const s=rows.find((x:any)=>x.token===token&&new Date(x.expiresAt).getTime()>Date.now());if(!s)return null;const all=await employeeAccounts();return all.find(x=>x.id===s.accountId)||null;}
export const handler=router({
 'POST /api/login':[async ctx=>{const b=ctx.body as {username?:string;password?:string;loginMode?:'dashboard'|'accountant'};if(!b.username||!b.password)return error('اسم المستخدم وكلمة المرور مطلوبان',400);const all=await accounts();const a=all.find(x=>x.username?.toLowerCase()===b.username!.trim().toLowerCase());if(!a?.passwordHash||await hashPassword(b.password)!==a.passwordHash)return error('اسم المستخدم أو كلمة المرور غير صحيحة',401);if(b.loginMode==='dashboard'&&a.role==='accounts')return error('هذا الحساب خاص ببرنامج المحاسب، وليس الداش بورد',403);if(b.loginMode==='accountant'&&a.role!=='accounts')return error('هذا الحساب خاص بالداش بورد، وليس برنامج المحاسب',403);const token=crypto.randomUUID();const expiresAt=new Date(Date.now()+2592000000).toISOString();const [id]=await db.add('dashboard_sessions',[{token,accountId:a.id,expiresAt}]);if(!id)return error('تعذر تسجيل الدخول',500);return {statusCode:200,headers:{'Content-Type':'application/json','Set-Cookie':cookieHeader(token)},body:JSON.stringify({account:{id:a.id,name:a.name,role:a.role,username:a.username,permissions:a.permissions||DEFAULT_PERMISSIONS}})};}],
 'POST /api/logout':[async()=>({statusCode:200,headers:{'Content-Type':'application/json','Set-Cookie':cookieHeader('',0)},body:JSON.stringify({ok:true})})],
 'GET /api/dashboard-data':[async ctx=>{const m=await current(ctx);if(!m)return error('غير مصرح',401);const out:any={employees:[],branches:[],attendance:[],overtime:[],money:[],audit:[],accounts:[],employeeAccounts:[],me:m};if(canView(m,'الموظفين')||canView(m,'المرتبات')||canView(m,'التقارير')||canView(m,'السُلف والخصومات')||canView(m,'المكافآت والتسويات'))out.employees=await list('employees');if(canView(m,'الفروع')||canView(m,'الموظفين')||canView(m,'التقارير'))out.branches=await list('branches');if(canView(m,'الحضور والانصراف')||canView(m,'التقارير'))out.attendance=await list('attendance');if(canView(m,'الحضور والانصراف')||canView(m,'المرتبات'))out.overtime=await list('overtime');if(canView(m,'السُلف والخصومات')||canView(m,'المكافآت والتسويات')||canView(m,'المرتبات')||canView(m,'التقارير'))out.money=await list('money');if(canView(m,'الإعدادات'))out.audit=await list('audit');if(isOwner(m)||canView(m,'حسابات الداش بورد'))out.accounts=await accounts();if(isOwner(m)&&canView(m,'الموظفين'))out.employeeAccounts=(await employeeAccounts()).map((x:any)=>({id:x.id,employeeId:x.employeeId,username:x.username,active:x.active!==false}));return json(out);}],
 'PUT /api/employee-accounts/:employeeId':[async ctx=>{const m=await current(ctx);if(!m||!isOwner(m))return error('فقط الـOwner يستطيع إدارة حسابات الموظفين',403);const employeeId=ctx.params.employeeId;const [employee]=await db.get<any>('employees',[employeeId]);if(!employee)return error('الموظف غير موجود',404);const b=ctx.body as any;const username=String(b.username||'').trim();const password=String(b.password||'');if(!username&&!password)return error('اكتب اسم المستخدم أو كلمة المرور',400);const all=await employeeAccounts();const normalized=username.replace(/\s+/g,'').toLowerCase();if(username&&all.some((x:any)=>x.employeeId!==employeeId&&String(x.username||'').replace(/\s+/g,'').toLowerCase()===normalized))return error('اسم المستخدم مستخدم بالفعل',409);const existing=all.find((x:any)=>x.employeeId===employeeId);if(existing){const next:any={...existing,username:username||existing.username,active:true};if(password){if(password.length<6)return error('كلمة المرور يجب ألا تقل عن 6 أحرف',400);next.passwordHash=await hashPassword(password);}const [ok]=await db.update('employee_accounts',[{id:existing.id,record:next}]);return ok?json({updated:true}):error('تعذر تعديل حساب الموظف',500);}if(!username||!password)return error('عند إنشاء الحساب يجب كتابة اسم المستخدم وكلمة المرور',400);if(password.length<6)return error('كلمة المرور يجب ألا تقل عن 6 أحرف',400);const [id]=await db.add('employee_accounts',[{employeeId,username,passwordHash:await hashPassword(password),active:true,createdAt:new Date().toISOString()}]);if(!id)return error('تعذر إنشاء حساب الموظف',500);await audit(m,'إنشاء حساب موظف',username);return json({id},201);}],
 'POST /api/employee-login':[async ctx=>{const b=ctx.body as any;if(!b.username||!b.password)return error('اسم المستخدم وكلمة المرور مطلوبان',400);const all=await employeeAccounts();const a=all.find((x:any)=>x.active!==false&&String(x.username||'').toLowerCase()===String(b.username).trim().toLowerCase());if(!a?.passwordHash||await hashPassword(String(b.password))!==a.passwordHash)return error('اسم المستخدم أو كلمة المرور غير صحيحة',401);const [employee]=await db.get<any>('employees',[a.employeeId]);if(!employee||employee.status==='موقوف')return error('حساب الموظف موقوف',403);const token=crypto.randomUUID();const expiresAt=new Date(Date.now()+2592000000).toISOString();const [id]=await db.add('employee_sessions',[{token,accountId:a.id,expiresAt}]);if(!id)return error('تعذر تسجيل الدخول',500);return {statusCode:200,headers:{'Content-Type':'application/json','Set-Cookie':employeeCookieHeader(token)},body:JSON.stringify({employee:{id:employee.id,name:employee.name,branch:employee.branch,role:employee.role}})};}],
 'POST /api/employee-logout':[async()=>({statusCode:200,headers:{'Content-Type':'application/json','Set-Cookie':employeeCookieHeader('',0)},body:JSON.stringify({ok:true})})],
 'GET /api/employee-me':[async ctx=>{const a=await employeeSession(ctx.event);if(!a)return error('غير مصرح',401);const [employee]=await db.get<any>('employees',[a.employeeId]);if(!employee)return error('الموظف غير موجود',404);return json({employee:{id:employee.id,name:employee.name,branch:employee.branch,role:employee.role}});} ],
 'GET /api/employee-attendance-today':[async ctx=>{const c=await employeeContext(ctx);if(!c)return error('غير مصرح',401);const n=cairoNow();const a=await todayAttendance(c.employee.id,n.date);const schedule=employeeSchedule(c.employee,n.date);return json({date:n.date,currentTime:n.time,dateLabel:new Intl.DateTimeFormat('ar-EG',{timeZone:'Africa/Cairo',weekday:'long',day:'numeric',month:'long'}).format(new Date()),schedule,attendance:a?{id:a.id,checkIn:a.checkIn||'',checkOut:a.checkOut||'',lateMinutes:Number(a.lateMinutes||0),status:a.status||'حاضر'}:null,employee:{id:c.employee.id,name:c.employee.name,branch:c.employee.branch,role:c.employee.role}});}],
 'GET /api/employee-summary':[async ctx=>{const c=await employeeContext(ctx);if(!c)return error('غير مصرح',401);const attendance=(await list('attendance')).filter((x:any)=>x.employeeId===c.employee.id).sort((a:any,b:any)=>String(b.date).localeCompare(String(a.date)));const money=(await list('money')).filter((x:any)=>x.employeeId===c.employee.id);const advances=money.filter((x:any)=>x.type==='سلفة').reduce((s:number,x:any)=>s+Number(x.amount||0),0);const deductions=money.filter((x:any)=>x.type==='خصم').reduce((s:number,x:any)=>s+Number(x.amount||0),0);const bonuses=money.filter((x:any)=>x.type==='مكافأة').reduce((s:number,x:any)=>s+Number(x.amount||0),0);const base=c.employee.payType==='شهري'?Number(c.employee.rate||0):Number(c.employee.rate||0)*Number(c.employee.dailyHours||0)*26;const remaining=Math.max(0,base+bonuses-deductions-advances);const n=cairoNow();return json({employee:{id:c.employee.id,name:c.employee.name,branch:c.employee.branch,role:c.employee.role,payType:c.employee.payType,rate:Number(c.employee.rate||0)},today:{date:n.date,schedule:employeeSchedule(c.employee,n.date)},weeklySchedule:c.employee.weekSchedule||{},attendance:attendance.map((x:any)=>({id:x.id,date:x.date,checkIn:x.checkIn||'',checkOut:x.checkOut||'',lateMinutes:Number(x.lateMinutes||0),workMinutes:Number(x.workMinutes||0),workHours:Number(x.workHours||0),status:x.status||'حاضر'})),financial:{base,advances,deductions,bonuses,remaining},money:money.map((x:any)=>({id:x.id,type:x.type,amount:Number(x.amount||0),reason:x.reason||'',date:x.date||''}))});}],
 'POST /api/employee-attendance/check-in':[async ctx=>{const c=await employeeContext(ctx);if(!c)return error('غير مصرح',401);const n=cairoNow();const existing=await todayAttendance(c.employee.id,n.date);if(existing?.checkIn)return error('تم تسجيل الحضور بالفعل',409);const late=lateMinutesFor(c.employee,n.date,n.time);const record={employeeId:c.employee.id,date:n.date,checkIn:n.time,checkOut:'',status:'حاضر',lateMinutes:late,source:'employee_app',createdAt:new Date().toISOString()};const [id]=await db.add('attendance',[record]);if(!id)return error('تعذر تسجيل الحضور',500);return json({date:n.date,currentTime:n.time,schedule:employeeSchedule(c.employee,n.date),attendance:{id,checkIn:n.time,checkOut:'',lateMinutes:late,status:'حاضر'},employee:{id:c.employee.id,name:c.employee.name,branch:c.employee.branch,role:c.employee.role}},201);}],
 'POST /api/employee-attendance/check-out':[async ctx=>{const c=await employeeContext(ctx);if(!c)return error('غير مصرح',401);const n=cairoNow();const existing=await todayAttendance(c.employee.id,n.date);if(!existing?.checkIn)return error('لا يمكن تسجيل الانصراف قبل الحضور',400);if(existing.checkOut)return error('تم تسجيل الانصراف بالفعل',409);const checkOut=n.time;const [h1,m1]=String(existing.checkIn).split(':').map(Number);const [h2,m2]=checkOut.split(':').map(Number);let mins=(h2*60+m2)-(h1*60+m1);if(mins<0)mins+=1440;const [ok]=await db.update('attendance',[{id:existing.id,record:{...existing,checkOut,workMinutes:mins,workHours:Number((mins/60).toFixed(2))}}]);if(!ok)return error('تعذر تسجيل الانصراف',500);return json({date:n.date,currentTime:checkOut,schedule:employeeSchedule(c.employee,n.date),attendance:{id:existing.id,checkIn:existing.checkIn,checkOut,lateMinutes:Number(existing.lateMinutes||0),status:existing.status||'حاضر',workMinutes:mins,workHours:Number((mins/60).toFixed(2))},employee:{id:c.employee.id,name:c.employee.name,branch:c.employee.branch,role:c.employee.role}},200);}],
 'POST /api/records/:table':[async ctx=>{const m=await current(ctx);if(!m)return error('غير مصرح',401);const table=ctx.params.table as Table;if(!TABLES.includes(table))return error('قسم غير صحيح',404);if(m.role!=='owner'&&!canView(m,sectionFor(table)))return error('ليس لديك صلاحية رؤية هذا القسم',403);if(m.role!=='owner'&&!canAction(m,'add'))return error('ليس لديك صلاحية الإضافة',403);const [id]=await db.add(table,[ctx.body]);if(!id)return error('تعذر الحفظ',500);await audit(m,'إضافة',`${table} — ${id}`);return json({id},201);}],
 'PUT /api/records/:table/:id':[async ctx=>{const m=await current(ctx);if(!m)return error('غير مصرح',401);const table=ctx.params.table as Table;if(!TABLES.includes(table))return error('قسم غير صحيح',404);if(!isOwner(m)&&(!canView(m,sectionFor(table))||!canAction(m,'edit')))return error('ليس لديك صلاحية التعديل',403);const [old]=await db.get(table,[ctx.params.id]);if(!old)return error('السجل غير موجود',404);const [ok]=await db.update(table,[{id:ctx.params.id,record:ctx.body as Record<string,unknown>}]);if(!ok)return error('تعذر التعديل',500);await audit(m,'تعديل',`${table} — ${ctx.params.id}`);return json({updated:true});}],
 'DELETE /api/records/:table/:id':[async ctx=>{const m=await current(ctx);if(!m||!isOwner(m))return error('الحذف متاح للـOwner فقط',403);const table=ctx.params.table as Table;if(!TABLES.includes(table))return error('قسم غير صحيح',404);const [ok]=await db.delete(table,[ctx.params.id]);if(!ok)return error('تعذر الحذف',500);await audit(m,'حذف',`${table} — ${ctx.params.id}`);return json({deleted:true});}],
 'POST /api/dashboard-accounts':[async ctx=>{const m=await current(ctx);if(!m||!isOwner(m))return error('فقط الـOwner يستطيع إضافة الحسابات',403);const b=ctx.body as any;if(!b.name?.trim()||!b.username?.trim()||!b.password)return error('الاسم واسم المستخدم وكلمة المرور مطلوبون',400);if(b.password.length<6)return error('كلمة المرور يجب ألا تقل عن 6 أحرف',400);const all=await accounts();const normalizedUsername=b.username.trim().replace(/\s+/g,'').toLowerCase();if(all.some(x=>x.username?.trim().replace(/\s+/g,'').toLowerCase()===normalizedUsername))return error('اسم المستخدم مستخدم بالفعل. راجع قسم حسابات الداش بورد للتأكد من عدم وجود حساب بنفس الاسم.',409);const role:Role=b.role==='owner'?'owner':'accounts';const permissions=role==='owner'?{view:Object.fromEntries(SECTIONS.map(x=>[x,true])),actions:{add:true,edit:true,delete:true,approve:true,manageAccounts:true}}:{view:{...DEFAULT_PERMISSIONS.view,...(b.permissions?.view||{})},actions:{...DEFAULT_PERMISSIONS.actions,...(b.permissions?.actions||{})}};const [id]=await db.add('dashboard_accounts',[{userId:'',email:'',name:b.name.trim(),username:b.username.trim(),passwordHash:await hashPassword(b.password),role,permissions}]);if(!id)return error('تعذر إنشاء الحساب',500);await audit(m,'إنشاء حساب داش بورد',b.username.trim());return json({id},201);}],
 'PUT /api/dashboard-accounts/:id':[async ctx=>{const m=await current(ctx);if(!m||!isOwner(m))return error('فقط الـOwner يستطيع تعديل الحسابات',403);const b=ctx.body as any;const [old]=await db.get('dashboard_accounts',[ctx.params.id]);if(!old)return error('الحساب غير موجود',404);const all=await accounts();if(b.username&&all.some(x=>x.id!==ctx.params.id&&x.username?.toLowerCase()===b.username.trim().toLowerCase()))return error('اسم المستخدم مستخدم بالفعل',409);const next:any={...old,name:b.name?.trim()||old.name,username:b.username?.trim()||old.username,role:b.role==='owner'?'owner':'accounts',permissions:b.role==='owner'?{view:Object.fromEntries(SECTIONS.map(x=>[x,true])),actions:{add:true,edit:true,delete:true,approve:true,manageAccounts:true}}:b.permissions||old.permissions||DEFAULT_PERMISSIONS};if(b.password){if(b.password.length<6)return error('كلمة المرور يجب ألا تقل عن 6 أحرف',400);next.passwordHash=await hashPassword(b.password);}const [ok]=await db.update('dashboard_accounts',[{id:ctx.params.id,record:next}]);return ok?json({updated:true}):error('تعذر تعديل الحساب',500);}],
 'DELETE /api/dashboard-accounts/:id':[async ctx=>{const m=await current(ctx);if(!m||!isOwner(m))return error('فقط الـOwner يستطيع الحذف',403);const [ok]=await db.delete('dashboard_accounts',[ctx.params.id]);return ok?json({deleted:true}):error('تعذر الحذف',500);}]
});
